//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BM_TRANS_TYPE
    {
        public string MERCHANT_NO { get; set; }
        public string TRANS_TYPE { get; set; }
        public string FILE_TRANS_TYPE { get; set; }
        public string FILE_TRANS_DESC { get; set; }
        public string FILE_SUB_TYPE { get; set; }
        public string SUB_TYPE_DESC { get; set; }
        public string SETTLE_FLG { get; set; }
        public string CONTRACT_TYPE { get; set; }
        public string SETTLE_TYPE { get; set; }
        public decimal SETTLE_SIGN { get; set; }
        public string TR_TRANS_TYPE { get; set; }
        public string TR_FILE_TRANS_TYPE { get; set; }
        public string TR_FILE_TRANS_DESC { get; set; }
        public string TR_FILE_SUB_TYPE { get; set; }
        public string TR_SUB_TYPE_DESC { get; set; }
        public string ACT_NAME_ICASH { get; set; }
        public string ARAP_ICASH { get; set; }
        public string RPT_ISSHOW_ICASH { get; set; }
        public string RPT_SHOW_ORDER_ICASH { get; set; }
        public string ACT_NAME_MERCHANT { get; set; }
        public string ACT_SEQ_MERCHANT { get; set; }
        public string ACT_NO_MERCHANT { get; set; }
        public decimal SETTLE_SIGN_MERCHANT { get; set; }
        public string ARAP_MERCHANT { get; set; }
        public string RPT_ISSHOW_MERCHANT { get; set; }
        public string RPT_SHOW_ORDER_MERCHANT { get; set; }
    }
}
