//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GM_ADJ_APPLICATION
    {
        public int FORM_ID { get; set; }

        [Display(Name = "申請日期")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyyMMdd}")]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "Date can only be 8 characters.")]
        public string APP_DATE { get; set; }

        [Display(Name = "營運日起")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyyMMdd}")]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "Date can only be 8 characters.")]
        public string OPP_DATE_START { get; set; }

        [Display(Name = "營運日迄")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyyMMdd}")]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "Date can only be 8 characters.")]
        public string OPP_DATE_END { get; set; }

        [Display(Name = "本表編號")]
        public string FORM_SERIAL { get; set; }

        [Display(Name = "合併結帳日")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyyMMdd}")]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "Date can only be 8 characters.")]
        public string RCPT_DATE { get; set; }
        public string MODIFIABLE { get; set; }

        [Display(Name = "申請調整說明")]
        public string ADJ_REMARK { get; set; }

        [Display(Name = "回覆結果說明")]
        public string REPLY_REMARK { get; set; }

        [Display(Name = "特約機構代號")]
        public string MERCHANT_NO { get; set; }
        public string CREATE_DATETIME { get; set; }
        public string UPDATE_DATETIME { get; set; }
    }
}
