SELECT E_DATE,'已餘額返還' AS E_TYPE,CARD_ID,(SELECT TOP 1 BANK_NAME FROM CM_BANK_D WHERE CA_DPT=LEFT(a.CARD_ID,2)) AS BANK_NAME,T_TYPE,T_DATE,CAST(T_VALUE AS BIGINT) AS NEW_VALUE,LSN,PSN FROM CM_TXEXCEPT_D a WHERE E_TYPE = 'E011' 
AND T_TYPE <> '58' --'排除鎖卡'
AND RETURN_CODE = '00000000'
AND LEFT(CARD_ID,2) IN (SELECT CA_DPT FROM CM_BANK_D WHERE MERCHANT_NO=CASE WHEN @bank='' THEN MERCHANT_NO ELSE @bank END)
AND CARD_ID = CASE WHEN @cardId ='' THEN CARD_ID ELSE @cardId END
AND E_DATE BETWEEN @sDate AND @eDate