--DECLARE @EXEC_CPT_DATE VARCHAR(8) = '20200401'
--DECLARE @YEARMONTH VARCHAR(8) = '20200301'
DECLARE @EXEC_YM VARCHAR(8) = CONVERT(VARCHAR, DATEADD(MONTH,1,CONVERT(datetime,@YEARMONTH,112)),112)
--DECLARE @NO1 VARCHAR(3) = '001' --
--DECLARE @NO2 VARCHAR(4) = '0010' --
--DECLARE @DATE_RANGE VARCHAR(3) = 'ALL'

--SELECT @EXEC_YM
--DECLARE @SCHEMAID VARCHAR(4)  = 'NCCC'
--DECLARE @AB_MERCHANT_NO VARCHAR(50) = '01508949'

DECLARE @EXEC_SDATE VARCHAR(8)
DECLARE @EXEC_EDATE VARCHAR(8)


SELECT @EXEC_SDATE = GET_SUM_DATE.SDATE,
       @EXEC_EDATE = GET_SUM_DATE.EDATE
FROM
(
	SELECT
		CASE WHEN SUM_DAY_S = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1				, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_YM) + (SUM_MON_S + 1), '')), 112)
								   ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + SUM_DAY_S	, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_YM) + (SUM_MON_S + 0), '')), 112) END AS 'SDATE',
		CASE WHEN SUM_DAY_E = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1				, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_YM) + (SUM_MON_E + 1), '')), 112)
								   ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + SUM_DAY_E	, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_YM) + (SUM_MON_E + 0), '')), 112) END AS 'EDATE'
		,SUM_DAY_S,SUM_DAY_E
	FROM	GM_CONTRACT_M
	WHERE	MERCHANT_NO = (select top 1 MERCHANT_NO from GM_MERCHANT where MERCH_SCHEMAID = '{0}' and MERCHANT_NO <> @AB_MERCHANT_NO)
		AND	@EXEC_CPT_DATE BETWEEN EFF_DATE_FROM AND EFF_DATE_TO
)GET_SUM_DATE

--SELECT @EXEC_SDATE,@EXEC_EDATE

INSERT INTO GM_MERCHANT_ACT_DATA_TEMP
SELECT 
		'0001' as num,
		@EXEC_CPT_DATE as CPT_DATE,
		MERCHANT_NO_ACT_M,
		--Case when M2.MERCHANT_SUB_STNAME is null then M1.MERCHANT_NAME else M2.MERCHANT_SUB_STNAME end 'MERCHANT_NAME',
		--M1.MERCHANT_STNAME ,
		--CASE WHEN @TAX_NO = 'N' THEN ISNULL(cast(ROUND(cast(ROUND((DATA.sumPCHA-DATA.sumPCHRA)*DATA.P_CM_AM,0) as decimal(20,5))* 0.05,0) as bigint),0) + ISNULL(cast(ROUND((DATA.sumPCHA-DATA.sumPCHRA)*DATA.P_CM_AM,0) as bigint),0) ELSE ISNULL(cast(ROUND((DATA.sumPCHA-DATA.sumPCHRA)*DATA.P_CM_AM,0) as bigint),0) END	as 'FEE_AMT',--2019.8.7 增加
		
		ISNULL(CONVERT(bigint,ROUND(SUM(FEE_AMT) / 1.05,0)),0)  as 'DIS_FEE_1', --未稅
		ISNULL(SUM(FEE_AMT) -CONVERT(bigint,ROUND(SUM(FEE_AMT) / 1.05,0)),0)  as 'FEE_AMT_1', --稅額
		--CASE WHEN FEE_DAY = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_CPT_DATE) + (1), '')), 112)
		--ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + FEE_DAY	, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_CPT_DATE) + (0), '')), 112) END AS FEE_DAY, --計算手續費預計收款日
		 CONVERT(VARCHAR,DATEADD(DAY,-1, DATEADD(MONTH,1,@YEARMONTH)),112) AS FEE_DAY_1 , --計算手續費預計收款日
		'', --發票號碼 預設空白
		'0001' AS TYPE_NUM, --列號
		'9' as NUM_TYPE, --類別 固定9
		ISNULL(CONVERT(bigint,ROUND(SUM(FEE_AMT) / 1.05,0)),0)   as 'DIS_FEE_2', --未稅
		ISNULL(SUM(FEE_AMT) -CONVERT(bigint,ROUND(SUM(FEE_AMT) / 1.05,0)),0) 'FEE_AMT_2', --稅額
		LEFT(CONVERT(VARCHAR ,DATEADD (MONTH , -1 , CONVERT(DATE,@EXEC_YM,112) ),112),6) +' 消費手續費-'+ MERCHANT_STNAME AS 'NAME_1' , --品名
		'461102' AS ACCOUNTING, --會科
		DEPARTMENT, --部門
		CONVERT(VARCHAR,DATEADD(DAY,-1, DATEADD(MONTH,1,@YEARMONTH)),112) AS FEE_DAY_2, --預計兌現日
		PROJECT_NO, --專案代號
		'', --備註2
		'', --B2C統一編號
		'1', --數量 
		'6111' as SNO, --日扣-非關係人 固定6111 
		0
		FROM 
(SELECT CPT_DATE ,
REPLACE(g.MERCHANT_NAME,' ','') MERCHANT_NAME,
--ISNULL(ga.merchant_stname,'***'+g.MERCHANT_STNAME) merchant_stname,
CASE WHEN MERCHANT_NO_ACT IS NULL THEN '***'+g.MERCHANT_STNAME 
WHEN GA.MERCHANT_STNAME IS NULL THEN g.MERCHANT_STNAME 
ELSE GA.MERCHANT_STNAME END AS merchant_stname,
ISNULL(ga.merchant_no_act_m,'') merchant_no_act_m,
 g.MERCHANT_NO,
TRANS_AMT ,
FEE_RATE * 100 FEE_RATE,
dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC) FEE_AMT,
TRANS_AMT-dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC) PAY_NET,
REMITTANCE_DATE,
ACCOUNTING,
DEPARTMENT,PROJECT_NO,FEE_DAY
FROM {0}.TM_FEE_TYPE_DATA_D a JOIN GM_MERCHANT g
ON a.MERCHANT_NO = g.MERCHANT_NO
LEFT JOIN GM_MERCHANT_ACT ga
ON a.MERCHANT_NO = ga.merchant_no
WHERE CONTRACT_TYPE = 'P1' AND FEE_CAL_FLG = 'AM' AND FEE_KIND = 'CM'
AND a.MERCHANT_NO <>  @AB_MERCHANT_NO
AND ga.REM_TYPE IN ('A004','C001') AND ga.SETTLE_RULE = 'D'
--AND a.MERCHANT_NO in (SELECT MERCHANT_NO FROM GM_REM_FEE_M WHERE CONTRACT_TYPE = 'P1' AND REM_TYPE IN ('D','W'))
AND a.MERCHANT_NO IN (SELECT MERCHANT_NO FROM GM_CONTRACT_M WHERE SUM_DAY_S = CASE WHEN @DATE_RANGE = 'ALL' THEN SUM_DAY_S ELSE @DATE_RANGE END)
AND a.MERCHANT_NO IN (SELECT MERCHANT_NO FROM GM_MERCHANT_TYPE_D WHERE GROUP_ID IN ({1}))
AND CPT_DATE BETWEEN @EXEC_SDATE AND @EXEC_EDATE
AND ga.INVOICE_RULE = @INVOICE_RULE
AND ga.SHOW_FLG = 'Y'
) A
GROUP BY ACCOUNTING,
DEPARTMENT,PROJECT_NO,MERCHANT_NO_ACT_M,merchant_stname
HAVING ISNULL(CONVERT(bigint,ROUND(SUM(FEE_AMT) / 1.05,0)),0)  <> 0


