      Declare @EXEC_MERCHANT_NO varchar(20) = 'ALL' --
    --  Declare @CPT_DATE varchar(8) = '20190311' --
    --  DECLARE @NO1 VARCHAR(3) = '001' --
  --    DECLARE @NO2 VARCHAR(4) = '0010' --
	  
DECLARE @TabeRpt TABLE (CPT_DATE varchar(8),
						MERCHANT_NO varchar(10),
						total_LOAD varchar(10),
						total_PCHR varchar(10),
						total_PCH varchar(10),
						total_LOADR varchar(10),
						total_LOADNet varchar(10),
						total_UTUT3 varchar(10),
						total_UTUT3R varchar(10),
						total_PCHNet varchar(10),
						total_Net NUMERIC(10,0),
						total_AUTOLOAD74 varchar(10),
						total_AUTOLOAD75 varchar(10),
						total_BULOAD79 varchar(10));

DECLARE @TOTAL TABLE 
	(TITLE VARCHAR(2),
	BUSINESS_DATE VARCHAR(8),
	NO1 VARCHAR(15),
	NO2 VARCHAR(4),
	ROWID VARCHAR(4),
	ACC_NO VARCHAR(20),
	S1 VARCHAR(1),
	ACC_CODE VARCHAR(2),
	NET_AMT VARCHAR(15),
	MERCHANT_NO_ACT VARCHAR(50),
	S2 VARCHAR(1),
	DOLLAR_NAME VARCHAR(10),
	RATE VARCHAR(10),
	S3 VARCHAR(1),
	MERCHANT_NOTE VARCHAR(100))


--set @CPT_DATE = @EXEC_CPT_DATE_B;

--WHILE(@CPT_DATE <= @EXEC_CPT_DATE_E)
begin
	insert @TabeRpt
	SELECT	@CPT_DATE '清算日', GM.MERCHANT_NO as MERCHANT_NO,
			isnull(G.TLOADA,0)				'加值'		,
			isnull(G.TPCHRA,0) - (isnull(G.TUT_R_AMT,0) + isnull(G.TUT3_R_AMT,0))	'購貨取消'	,
			isnull(G.TPCHA,0) - (isnull(G.TUT_AMT,0) + isnull(G.TUT3_AMT,0)) 		'購貨'		,
			isnull(G.TLOADRA,0)				'加值取消'	,
			isnull(G.TLOADA-G.TLOADRA,0)	'加值淨額'	,
			(isnull(G.TUT_AMT,0) + isnull(G.TUT3_AMT,0))		'代收售',
			(isnull(G.TUT_R_AMT,0) + isnull(G.TUT3_R_AMT,0))	'代收售取消',
			isnull(G.TPCHA-G.TPCHRA,0)							'購貨及代收售淨額'	,
			isnull((G.TPCHA-G.TPCHRA)- (G.TLOADA-G.TLOADRA),0)	'特約機構總淨額',
			isnull(G.TLOAD74_AMT,0)			'自動加值', 
			isnull(G.TLOAD75_AMT,0)			'代行授權自動加值', 
			isnull(G.TBULOAD79_AMT,0)		'企業加值'
	FROM GM_MERCHANT GM LEFT OUTER JOIN
	(
		SELECT	T.CPT_DATE,
				T.MERCHANT_NO,
				SUM(ISNULL(T.PCHA	,0))		TPCHA	,
				SUM(ISNULL(T.PCHC	,0))		TPCHC	,
				SUM(ISNULL(T.PCHRA	,0))		TPCHRA	,
				SUM(ISNULL(T.PCHRC	,0))		TPCHRC	,
				SUM(ISNULL(T.LOADA	,0))		TLOADA	,
				SUM(ISNULL(T.LOADC	,0))		TLOADC	,
				SUM(ISNULL(T.LOADRA	,0))		TLOADRA	,
				SUM(ISNULL(T.LOADRC	,0))		TLOADRC	,
				SUM(ISNULL(T.LOAD74_AMT	,0))	TLOAD74_AMT	,
				SUM(ISNULL(T.LOAD75_AMT	,0))	TLOAD75_AMT	,
				SUM(ISNULL(T.UT_AMT	,0))		TUT_AMT	,
				SUM(ISNULL(T.UT3_AMT	,0))	TUT3_AMT	,
				SUM(ISNULL(T.UT_R_AMT	,0))	TUT_R_AMT	,
				SUM(ISNULL(T.UT3_R_AMT	,0))	TUT3_R_AMT	,
				SUM(ISNULL(T.BULOAD79_AMT	,0))	TBULOAD79_AMT	
		FROM
		(	SELECT	CPT_DATE,
					MERCHANT_NO,
					SUM(isnull(PCH_AMT  ,0))	PCHA,
					SUM(isnull(PCH_CNT  ,0))	PCHC ,
					SUM(isnull(PCHR_AMT ,0)) 	PCHRA,
					SUM(isnull(PCHR_CNT ,0))	PCHRC,
					SUM(isnull(LOAD_AMT ,0)) 	LOADA,
					SUM(isnull(LOAD_CNT ,0))	LOADC,
					SUM(isnull(LOADR_AMT,0))	LOADRA,
					SUM(isnull(LOADR_CNT,0))	LOADRC,
					0	LOAD74_AMT,
					0	LOAD75_AMT,
					0	UT_AMT,
					0	UT3_AMT,
					0	UT_R_AMT,
					0	UT3_R_AMT,
					0	BULOAD79_AMT
			FROM AM_ISET_MERC_TRANS_LOG_D
			WHERE SRC_FLG='TXLOG'
			 
			  AND CPT_DATE = @CPT_DATE
			GROUP BY CPT_DATE,MERCHANT_NO
			union all  
			SELECT	CPT_DATE,
					MERCHANT_NO,
					0	PCHA,
					0	PCHC ,
					0 	PCHRA,
					0	PCHRC,
					0 	LOADA,
					0	LOADC,
					0	LOADRA,
					0	LOADRC,
					0	LOAD74_AMT,
					0	LOAD75_AMT,
					SUM(isnull(UT_AMT,0))	UT_AMT,
					SUM(isnull(UT3_AMT,0))	UT3_AMT,
					0	UT_R_AMT,
					0	UT3_R_AMT,
					0	BULOAD79_AMT
			FROM AM_ISET_MERC_TRANS_UTLOG_D
			WHERE SRC_FLG='TXLOG'
			  
			  AND CPT_DATE = @CPT_DATE
			  AND TRANS_TYPE='21'
			GROUP BY CPT_DATE,MERCHANT_NO
			union all  
			SELECT	CPT_DATE,
					MERCHANT_NO,
					0	PCHA,
					0	PCHC ,
					0 	PCHRA,
					0	PCHRC,
					0 	LOADA,
					0	LOADC,
					0	LOADRA,
					0	LOADRC,
					0	LOAD74_AMT,
					0	LOAD75_AMT,
					0	UT_AMT,
					0	UT3_AMT,
					SUM(isnull(UT_AMT,0))	UT_R_AMT,
					SUM(isnull(UT3_AMT,0))	UT3_R_AMT,
					0	BULOAD79_AMT
			FROM AM_ISET_MERC_TRANS_UTLOG_D
			WHERE SRC_FLG='TXLOG'
			  
			  AND CPT_DATE = @CPT_DATE
			  AND TRANS_TYPE='23'
			GROUP BY CPT_DATE,MERCHANT_NO
			union all  
			SELECT  CPT_DATE,
					MERCHANT_NO,
					0	PCHA,
					0	PCHC ,
					0 	PCHRA,
					0	PCHRC,
					0 	LOADA,
					0	LOADC,
					0	LOADRA,
					0	LOADRC,
					isnull(sum(LOAD74_AMT),0) + isnull(sum(LOAD77_AMT),0) as LOAD74_AMT, --(add by 20160415 rita 新增 77離線自動加值)
					isnull(sum(LOAD75_AMT),0) as LOAD75_AMT,
					0	UT_AMT,
					0	UT3_AMT,
					0	UT_R_AMT,
					0	UT3_R_AMT,
					0	BULOAD79_AMT
			from GM_BANK_CPT_SUM 
			where  CPT_DATE = @CPT_DATE
			group by CPT_DATE,MERCHANT_NO
			union all  
			SELECT  CPT_DATE,
					MERCHANT_NO,
					0	PCHA,
					0	PCHC ,
					0 	PCHRA,
					0	PCHRC,
					0 	LOADA,
					0	LOADC,
					0	LOADRA,
					0	LOADRC,
					0	LOAD74_AMT, 
					0	LOAD75_AMT,
					0	UT_AMT,
					0	UT3_AMT,
					0	UT_R_AMT,
					0	UT3_R_AMT,
					isnull(sum(BULOAD79_AMT),0) as	BULOAD79_AMT
			from GM_CPT_SUM_AUTO_D 
			where CPT_DATE = @CPT_DATE
			group by CPT_DATE,MERCHANT_NO
		) T 
		group by CPT_DATE,MERCHANT_NO 
	) G
	ON GM.MERCHANT_NO = G.MERCHANT_NO    
	where GM.MERCHANT_TYPE <> 'BANK' 
	and GM.MERCHANT_NO not in ('54650113','54650114') 
	ORDER BY 1,GM.MERCHANT_TYPE,GM.SAM_TYPE desc,GM.MERC_GROUP desc,GM.MERCHANT_NO

end
INSERT INTO @TOTAL
SELECT 'E' AS TITLE,
		convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
		'W'+RIGHT(CPT_DATE,6)+@NO1 AS NO1,
		@NO2 AS NO2,
		'0000' AS ROWID,
		'226801' AS ACC_NO,
		'' AS S1,
		'D' AS ACC_CODE ,
		SUM(total_Net) AS NET_AMT,
		'' AS MERCHANT_NO_ACT,
		'' AS S2,
		'NT$' AS DOLLAR_NAME,
		'1' AS RATE,
		'' AS S3,
		'卡務餘額異動' AS MERCHANT_NOTE
		

FROM  @TabeRpt A
inner join GM_MERCHANT GM on A.MERCHANT_NO = GM.MERCHANT_NO
GROUP BY CPT_DATE
-------------------
-------------------
UNION ALL 






        SELECT 'E' AS TITLE,BUSINESS_DATE,NO1,NO2,
		RIGHT('0000'+CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY MERCHANT_NO_ACT)),4) AS ROWID,
		ACC_NO,
		'' AS S1,
		CASE WHEN MERCHANT_NO_ACT IS NULL THEN '' ELSE ACC_CODE END AS ACC_CODE ,
		NET_AMT,
		MERCHANT_NO_ACT,
		'' AS S2,
		'NT$' AS DOLLAR_NAME,
		'1' AS RATE,
		'' AS S3,
		CASE WHEN MERCHANT_NOTE IS NULL THEN '***'+GM1.MERCHANT_NAME ELSE MERCHANT_NOTE END AS MERCHANT_NOTE
		
		FROM (

	SELECT	
			convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
			'W'+RIGHT(G.CPT_DATE,6)+@NO1 AS NO1,
			@NO2 AS NO2,
			CASE WHEN ISNULL(G.LOAD_NET,0) > 0 THEN M.LOAD_DEBIT ELSE M.LOAD_CREDIT END AS ACC_NO,
			'' AS N1,
			CASE WHEN ISNULL(G.LOAD_NET,0) > 0 THEN 'D' ELSE 'C' END AS ACC_CODE,
			ISNULL(G.LOAD_NET,0) - ISNULL(CASE WHEN G.MERCHANT_NO = '22555003' THEN 
				(select SUM(convert(int, TRANS_AMT))
				from isettle2.dbo.IM_OL_TXLOG_T_ICASH3 A
				inner join isettle2.dbo.CC_REGISTER_ICASH3 B on A.ICC_NO = B.CARD_NO
				where MERCHANT_NO = '22555003'
				and TRANS_TYPE = '22' 
				and FILE_TRANS_TYPE = '78' 
				and ZIP_FILE_NAME >= 'ICASH3_'+convert(varchar, dateadd(day,-1,convert(date,@CPT_DATE,112)), 112)+'000000'
				and ZIP_FILE_NAME <= 'ICASH3_'+convert(varchar, dateadd(day,-1,convert(date,@CPT_DATE,112)), 112)+'235959'
				and RETURN_CODE = '00000000') 
				ELSE 0 END,0) NET_AMT, --20200527 無人店扣薪加值
			GM.MERCHANT_NO_ACT,
			GM.MERCHANT_NOTE,
			G.MERCHANT_NO
			
			
			

			--isnull(G.TPCHA-G.TPCHRA,0)							'購貨及代收售淨額'	,
	FROM (
		SELECT	T.CPT_DATE,
				T.MERCHANT_NO,
				SUM(ISNULL(T.LOADA	,0)) - SUM(ISNULL(T.LOADRA	,0)) AS 'LOAD_NET',  
				SUM(ISNULL(T.PCHA	,0))- SUM(ISNULL(T.PCHRA	,0)) AS 'PCH_NET'
			
		FROM
		(	SELECT	CPT_DATE,
					MERCHANT_NO,
					SUM(isnull(PCH_AMT  ,0))	PCHA,
					SUM(isnull(PCH_CNT  ,0))	PCHC ,
					SUM(isnull(PCHR_AMT ,0)) 	PCHRA,
					SUM(isnull(PCHR_CNT ,0))	PCHRC,
					SUM(isnull(LOAD_AMT ,0)) 	LOADA,
					SUM(isnull(LOAD_CNT ,0))	LOADC,
					SUM(isnull(LOADR_AMT,0))	LOADRA,
					SUM(isnull(LOADR_CNT,0))	LOADRC,
					0	LOAD74_AMT,
					0	LOAD75_AMT,
					0	UT_AMT,
					0	UT3_AMT,
					0	UT_R_AMT,
					0	UT3_R_AMT,
					0	BULOAD79_AMT
			FROM AM_ISET_MERC_TRANS_LOG_D
			WHERE SRC_FLG='TXLOG'
			 
			  AND CPT_DATE = @CPT_DATE
			GROUP BY CPT_DATE,MERCHANT_NO
			union all  
			SELECT	CPT_DATE,
					MERCHANT_NO,
					0	PCHA,
					0	PCHC ,
					0 	PCHRA,
					0	PCHRC,
					0 	LOADA,
					0	LOADC,
					0	LOADRA,
					0	LOADRC,
					0	LOAD74_AMT,
					0	LOAD75_AMT,
					SUM(isnull(UT_AMT,0))	UT_AMT,
					SUM(isnull(UT3_AMT,0))	UT3_AMT,
					0	UT_R_AMT,
					0	UT3_R_AMT,
					0	BULOAD79_AMT
			FROM AM_ISET_MERC_TRANS_UTLOG_D
			WHERE SRC_FLG='TXLOG'
			 
			  AND CPT_DATE = @CPT_DATE
			  AND TRANS_TYPE='21'
			GROUP BY CPT_DATE,MERCHANT_NO
			union all  
			SELECT	CPT_DATE,
					MERCHANT_NO,
					0	PCHA,
					0	PCHC ,
					0 	PCHRA,
					0	PCHRC,
					0 	LOADA,
					0	LOADC,
					0	LOADRA,
					0	LOADRC,
					0	LOAD74_AMT,
					0	LOAD75_AMT,
					0	UT_AMT,
					0	UT3_AMT,
					SUM(isnull(UT_AMT,0))	UT_R_AMT,
					SUM(isnull(UT3_AMT,0))	UT3_R_AMT,
					0	BULOAD79_AMT
			FROM AM_ISET_MERC_TRANS_UTLOG_D
			WHERE SRC_FLG='TXLOG'
			  
			  AND CPT_DATE = @CPT_DATE
			  AND TRANS_TYPE='23'
			GROUP BY CPT_DATE,MERCHANT_NO
			
		) T 
		group by CPT_DATE,MERCHANT_NO 
		) G
		LEFT JOIN GM_MERCHANT_ACT GM
		ON G.MERCHANT_NO = GM.MERCHANT_NO
		LEFT JOIN GM_MERCHANT_ACT_MAPPING M
		ON GM.SET_GROUP = M.SET_GROUP
		WHERE LOAD_NET <> 0 AND ( GM.PAY_TYPE = '01' OR GM.PAY_TYPE IS NULL )
----------------------------加值
		UNION ALL 
----------------------------購貨
		SELECT	
			
			convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
			'W'+RIGHT(G.CPT_DATE,6)+@NO1 AS NO1,
			@NO2 AS NO2,
			CASE WHEN ISNULL(G.PCH_NET,0) > 0 THEN M.PCH_CREDIT ELSE M.PCH_DEBIT END AS ACC_NO,
			'' AS N1,
			CASE WHEN ISNULL(G.PCH_NET,0) > 0 THEN 'C' ELSE 'D' END AS ACC_CODE,
			ISNULL(G.PCH_NET,0)	NET_AMT,
			GM.MERCHANT_NO_ACT,
			GM.MERCHANT_NOTE,
			G.MERCHANT_NO

		

			--isnull(G.TPCHA-G.TPCHRA,0)							'購貨及代收售淨額'	,
	FROM (
		SELECT	T.CPT_DATE,
				T.MERCHANT_NO,
				SUM(ISNULL(T.LOADA	,0)) - SUM(ISNULL(T.LOADRA	,0)) AS 'LOAD_NET', 
				SUM(ISNULL(T.PCHA	,0))- SUM(ISNULL(T.PCHRA	,0)) AS 'PCH_NET'
		FROM
		(	SELECT	CPT_DATE,
					MERCHANT_NO,
					SUM(isnull(PCH_AMT  ,0))	PCHA,
					SUM(isnull(PCH_CNT  ,0))	PCHC ,
					SUM(isnull(PCHR_AMT ,0)) 	PCHRA,
					SUM(isnull(PCHR_CNT ,0))	PCHRC,
					SUM(isnull(LOAD_AMT ,0)) 	LOADA,
					SUM(isnull(LOAD_CNT ,0))	LOADC,
					SUM(isnull(LOADR_AMT,0))	LOADRA,
					SUM(isnull(LOADR_CNT,0))	LOADRC,
					0	LOAD74_AMT,
					0	LOAD75_AMT,
					0	UT_AMT,
					0	UT3_AMT,
					0	UT_R_AMT,
					0	UT3_R_AMT,
					0	BULOAD79_AMT
			FROM AM_ISET_MERC_TRANS_LOG_D
			WHERE SRC_FLG='TXLOG'
			  --AND MERCHANT_NO = case when @EXEC_MERCHANT_NO = 'ALL' then MERCHANT_NO else @EXEC_MERCHANT_NO end
			  AND CPT_DATE = @CPT_DATE
			GROUP BY CPT_DATE,MERCHANT_NO
			union all  
			SELECT	CPT_DATE,
					MERCHANT_NO,
					0	PCHA,
					0	PCHC ,
					0 	PCHRA,
					0	PCHRC,
					0 	LOADA,
					0	LOADC,
					0	LOADRA,
					0	LOADRC,
					0	LOAD74_AMT,
					0	LOAD75_AMT,
					SUM(isnull(UT_AMT,0))	UT_AMT,
					SUM(isnull(UT3_AMT,0))	UT3_AMT,
					0	UT_R_AMT,
					0	UT3_R_AMT,
					0	BULOAD79_AMT
			FROM AM_ISET_MERC_TRANS_UTLOG_D
			WHERE SRC_FLG='TXLOG'
			 
			  AND CPT_DATE = @CPT_DATE
			  AND TRANS_TYPE='21'
			GROUP BY CPT_DATE,MERCHANT_NO
			union all  
			SELECT	CPT_DATE,
					MERCHANT_NO,
					0	PCHA,
					0	PCHC ,
					0 	PCHRA,
					0	PCHRC,
					0 	LOADA,
					0	LOADC,
					0	LOADRA,
					0	LOADRC,
					0	LOAD74_AMT,
					0	LOAD75_AMT,
					0	UT_AMT,
					0	UT3_AMT,
					SUM(isnull(UT_AMT,0))	UT_R_AMT,
					SUM(isnull(UT3_AMT,0))	UT3_R_AMT,
					0	BULOAD79_AMT
			FROM AM_ISET_MERC_TRANS_UTLOG_D
			WHERE SRC_FLG='TXLOG'
			  
			  AND CPT_DATE = @CPT_DATE
			  AND TRANS_TYPE='23'
			GROUP BY CPT_DATE,MERCHANT_NO
			
		) T 
		group by CPT_DATE,MERCHANT_NO 
		) G
		LEFT JOIN GM_MERCHANT_ACT GM
		ON G.MERCHANT_NO = GM.MERCHANT_NO
		LEFT JOIN GM_MERCHANT_ACT_MAPPING M
		ON GM.SET_GROUP = M.SET_GROUP
		WHERE PCH_NET <> 0 AND  ( GM.PAY_TYPE = '01' OR GM.PAY_TYPE IS NULL )
	) A 
	LEFT JOIN GM_MERCHANT GM1
	ON A.MERCHANT_NO = GM1.MERCHANT_NO
------------------------
------------------------BY 門市 PAY_TYPE = 02
DECLARE @SCHEMAID VARCHAR(4) 
DECLARE @MERCHANT_NAME VARCHAR(50)
DECLARE A CURSOR FOR
SELECT MERCH_SCHEMAID,MERCHANT_STNAME FROM GM_MERCHANT WHERE MERCHANT_NO IN (SELECT distinct MERCHANT_NO FROM GM_MERCHANT_ACT WHERE PAY_TYPE = '02')
OPEN A
FETCH NEXT FROM A INTO @SCHEMAID,@MERCHANT_NAME
WHILE @@FETCH_STATUS = 0
BEGIN
INSERT INTO @TOTAL 
	EXEC ('
	
  SELECT ''E'' AS TITLE,BUSINESS_DATE,NO1,NO2,
		RIGHT(''0000''+CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY MERCHANT_NO_ACT)),4) AS ROWID,
		ACC_NO,
		'''' AS S1,
		CASE WHEN MERCHANT_NO_ACT IS NULL THEN '''' ELSE ACC_CODE END AS ACC_CODE ,
		NET_AMT,
		MERCHANT_NO_ACT,
		'''' AS S2,
		''NT$'' AS DOLLAR_NAME,
		''1'' AS RATE,
		'''' AS S3,
		MERCHANT_NOTE
	FROM 	(
	SELECT 		convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
				''W''+RIGHT(B.CPT_DATE,6)+'''+@NO1+''' AS NO1,
				'''+@NO2+''' AS NO2,
				CASE WHEN ISNULL(B.PCH_NET,0) > 0 THEN M.PCH_CREDIT ELSE M.PCH_DEBIT END AS ACC_NO,
				'''' AS N1,
				CASE WHEN ISNULL(B.PCH_NET,0) > 0 THEN ''C'' ELSE ''D'' END AS ACC_CODE,
				ISNULL(B.PCH_NET,0)	NET_AMT,
				GMS.MERCHANT_NO_ACT,
				CASE WHEN GMS.MERCHANT_NOTE IS NULL  THEN ''***''+'''+@MERCHANT_NAME+'''+BS.STO_NAME_LONG ELSE GMS.MERCHANT_NOTE END AS MERCHANT_NOTE
				 FROM 
	(
		SELECT CPT_DATE,STORE_NO,A.MERCHANT_NO,SUM(TRANS_AMT * SETTLE_SIGN) AS PCH_NET FROM '+@SCHEMAID+'.TM_SETTLE_DATA_D A
		JOIN '+@SCHEMAID+'.BM_TRANS_TYPE C
		ON A.TRANS_TYPE = C.TRANS_TYPE
		WHERE TR_TRANS_TYPE IN (''21'',''23'') AND SETTLE_TYPE = ''P''
		AND CPT_DATE = '''+@CPT_DATE+ '''
		GROUP BY CPT_DATE,STORE_NO,A.MERCHANT_NO
	) B
	LEFT JOIN GM_MERCHANT_ACT_STORE GMS
	ON B.MERCHANT_NO = GMS.MERCHANT_NO
	AND B.STORE_NO = GMS.STORE_NO
	LEFT JOIN GM_MERCHANT_ACT GA
	ON GMS.MERCHANT_NO = GA.MERCHANT_NO
	LEFT JOIN GM_MERCHANT_ACT_MAPPING M
	ON GA.SET_GROUP = M.SET_GROUP
	LEFT JOIN '+@SCHEMAID+'.BM_STORE_M BS
	ON B.STORE_NO = BS.STORE_NO

	UNION ALL

	SELECT 		convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
				''W''+RIGHT(B.CPT_DATE,6)+'''+@NO1+''' AS NO1,
				'''+@NO2+''' AS NO2,
				CASE WHEN ISNULL(B.PCH_NET,0) > 0 THEN M.LOAD_DEBIT ELSE M.LOAD_CREDIT END AS ACC_NO,
				'''' AS N1,
				CASE WHEN ISNULL(B.PCH_NET,0) > 0 THEN ''D'' ELSE ''C'' END AS ACC_CODE,
				ISNULL(B.PCH_NET,0)	NET_AMT,
				GMS.MERCHANT_NO_ACT,
				CASE WHEN GMS.MERCHANT_NOTE IS NULL  THEN ''***''+'''+@MERCHANT_NAME+'''+ BS.STO_NAME_LONG ELSE GMS.MERCHANT_NOTE END AS MERCHANT_NOTE
				 FROM 
	(
		SELECT CPT_DATE,STORE_NO,A.MERCHANT_NO,SUM(TRANS_AMT * SETTLE_SIGN) AS PCH_NET FROM '+@SCHEMAID+'.TM_SETTLE_DATA_D A
		JOIN '+@SCHEMAID+'.BM_TRANS_TYPE C
		ON A.TRANS_TYPE = C.TRANS_TYPE
		WHERE TR_TRANS_TYPE IN (''22'',''24'') AND SETTLE_TYPE = ''P''
		AND CPT_DATE = '''+ @CPT_DATE +'''
		GROUP BY CPT_DATE,STORE_NO,A.MERCHANT_NO
	) B
	LEFT JOIN GM_MERCHANT_ACT_STORE GMS
	ON B.MERCHANT_NO = GMS.MERCHANT_NO
	AND B.STORE_NO = GMS.STORE_NO
	LEFT JOIN GM_MERCHANT_ACT GA
	ON GMS.MERCHANT_NO = GA.MERCHANT_NO
	LEFT JOIN GM_MERCHANT_ACT_MAPPING M
	ON GA.SET_GROUP = M.SET_GROUP
	LEFT JOIN '+@SCHEMAID+'.BM_STORE_M BS
	ON B.STORE_NO = BS.STORE_NO
	) F
	WHERE NET_AMT <> 0 '
)
    FETCH NEXT FROM A INTO @SCHEMAID,@MERCHANT_NAME
END
CLOSE A
DEALLOCATE A

---- 北捷加值手續費----
-----------------------
INSERT INTO @TOTAL 
SELECT 'E' AS TITLE,
convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
'W'+RIGHT(A.CPT_DATE,6)+@NO1 AS NO1,
@NO2 AS NO2,
RIGHT('0000'+CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY MERCHANT_NO_ACT)),4) AS ROWID,
AP_DEBIT AS ACC_NO,
'' AS S1,
'D' AS ACC_CODE ,
FEE_AMT AS NET_AMT,
MERCHANT_NO_ACT,
'' AS S2,
'NT$' AS DOLLAR_NAME,
'1' AS RATE,
'' AS S3,
LEFT(convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 101),5)+ ' ' + MERCHANT_NOTE AS MERCHANT_NOTE
FROM GM_MERCHANT_ACT_TRT_LOADFEE A
JOIN GM_MERCHANT_ACT_TRT B
ON A.MERCHANT_NO = B.MERCHANT_NO
WHERE CPT_DATE = @CPT_DATE AND ARAP_ICASH = 'AP'

UNION ALL

SELECT 'E' AS TITLE,
convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
'W'+RIGHT(A.CPT_DATE,6)+@NO1 AS NO1,
@NO2 AS NO2,
RIGHT('0000'+CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY MERCHANT_NO_ACT)),4) AS ROWID,
AP_CREDIT AS ACC_NO,
'' AS S1,
'C' AS ACC_CODE ,
FEE_AMT AS NET_AMT,
MERCHANT_NO_ACT,
'' AS S2,
'NT$' AS DOLLAR_NAME,
'1' AS RATE,
'' AS S3,
LEFT(convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 101),5)+ ' ' + MERCHANT_NOTE AS MERCHANT_NOTE
FROM GM_MERCHANT_ACT_TRT_LOADFEE A
JOIN GM_MERCHANT_ACT_TRT B
ON A.MERCHANT_NO = B.MERCHANT_NO
WHERE CPT_DATE = @CPT_DATE AND ARAP_ICASH = 'AP'

---------------------------
---NCC北捷場域加值手續費---
---------------------------




--DECLARE @P1_NUM_PREC INT
--DECLARE @P1_TYPE_PREC varchar(8)
DECLARE @P1_FEE_RATE NUMERIC(15,5) = 0.01
--DECLARE @L1_NUM_PREC INT
--DECLARE @L1_TYPE_PREC varchar(8)
DECLARE @L1_FEE_RATE NUMERIC(15,5) = 0.004
--DECLARE @L2_NUM_PREC INT
--DECLARE @L2_TYPE_PREC varchar(8)
DECLARE @L2_FEE_RATE NUMERIC(15,5) = 0.0002
DECLARE @NCC_TRT_FILED TABLE 
(CPT_DATE varchar(10),MERCHANT_NO VARCHAR(20),PNET BIGINT,LNET BIGINT,ANET BIGINT,P1_FEE NUMERIC(15,5),L_FEE NUMERIC(15,5))


--SELECT @P1_FEE_RATE = FEE_RATE, @P1_NUM_PREC = NUM_PREC,@P1_TYPE_PREC = TYPE_PREC  FROM GM_CONTRACT_MUTI_MERC_D 
--WHERE CONTRACT_TYPE = 'P1'
--AND @CPT_DATE BETWEEN EFF_DATE_FROM AND EFF_DATE_TO 

--SELECT @L1_FEE_RATE = FEE_RATE, @L1_NUM_PREC = NUM_PREC,@L1_TYPE_PREC = TYPE_PREC  FROM GM_CONTRACT_MUTI_MERC_D 
--WHERE CONTRACT_TYPE = 'L1'
--AND @CPT_DATE BETWEEN EFF_DATE_FROM AND EFF_DATE_TO 

--SELECT @L2_FEE_RATE = FEE_RATE, @L2_NUM_PREC = NUM_PREC,@L2_TYPE_PREC = TYPE_PREC  FROM GM_CONTRACT_MUTI_MERC_D 
--WHERE CONTRACT_TYPE = 'L2'
--AND @CPT_DATE BETWEEN EFF_DATE_FROM AND EFF_DATE_TO 


INSERT @NCC_TRT_FILED
SELECT T1.CPT_DATE,T1.MERCHANT_NO,SUM(T1.PNET),SUM(T1.LNET),SUM(T1.ANET),
ROUND(SUM(T1.PNET * @P1_FEE_RATE),0) AS P1_FEE,
CONVERT(INT,ROUND(SUM(LNET * @L1_FEE_RATE + ANET * @L2_FEE_RATE),0)) AS L_FEE
FROM (
SELECT CPT_DATE,MERCHANT_NO,
SUM(ISNULL([21],0))-SUM(ISNULL([23],0)) AS PNET,
SUM(ISNULL([22],0))-SUM(ISNULL([24],0)) AS LNET,
SUM(ISNULL([74],0))+SUM(ISNULL([75],0))+SUM(ISNULL([77],0)) AS ANET
--dbo.fn_convertNum((SUM(ISNULL([21],0))-SUM(ISNULL([23],0))) * @P1_FEE_RATE,@P1_NUM_PREC,@P1_TYPE_PREC) ,
--(SUM(ISNULL([22],0))-SUM(ISNULL([24],0))) * @L1_FEE_RATE + (SUM(ISNULL([74],0))+SUM(ISNULL([75],0))+SUM(ISNULL([77],0))) * @L2_FEE_RATE

FROM 
(
select CPT_DATE,A.MERCHANT_NO,b.TR_TRANS_TYPE as TRANS_TYPE,TRANS_AMT from NCC.TM_SETTLE_DATA_D a
join NCC.BM_TRANS_TYPE b
on a.merchant_no = b.merchant_no 
AND A.TRANS_TYPE = B.TRANS_TYPE
where a.merchant_no IN (SELECT MERCHANT_NO from GM_FEEDBACK_MUTI_MERC_D where OM_GROUP = 'D_EXL_TRT')

and  CPT_DATE  = @CPT_DATE
) A
PIVOT(sum(TRANS_AMT) FOR TRANS_TYPE IN ([21],[22],[23],[24],[74],[77],[75])
) AS P1
group by CPT_DATE,MERCHANT_NO ) T1
GROUP BY T1.CPT_DATE,T1.MERCHANT_NO
--ORDER BY CPT_DATE,TRANS_DATE


INSERT INTO @TOTAL 
SELECT 'E' AS TITLE,
convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
'W'+RIGHT(A.CPT_DATE,6)+@NO1 AS NO1,
@NO2 AS NO2,
RIGHT('0000'+CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY B.MERCHANT_NO_ACT)),4) AS ROWID,
AP_DEBIT AS ACC_NO,
'' AS S1,
'D' AS ACC_CODE ,
L_FEE AS NET_AMT,
B.MERCHANT_NO_ACT,
'' AS S2,
'NT$' AS DOLLAR_NAME,
'1' AS RATE,
'' AS S3,
LEFT(convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 101),5)+ ' 加值手續費-' + B.MERCHANT_NOTE AS MERCHANT_NOTE
FROM @NCC_TRT_FILED A
JOIN GM_MERCHANT_ACT B
ON A.MERCHANT_NO = B.MERCHANT_NO
JOIN GM_MERCHANT_ACT_TRT C
ON C.MERCHANT_NO_ACT = '84894989'

WHERE CPT_DATE = @CPT_DATE 
AND A.L_FEE <> 0 

UNION ALL

SELECT 'E' AS TITLE,
convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
'W'+RIGHT(A.CPT_DATE,6)+@NO1 AS NO1,
@NO2 AS NO2,
RIGHT('0000'+CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY B.MERCHANT_NO_ACT)),4) AS ROWID,
AP_CREDIT AS ACC_NO,
'' AS S1,
'C' AS ACC_CODE ,
L_FEE AS NET_AMT,
B.MERCHANT_NO_ACT,
'' AS S2,
'NT$' AS DOLLAR_NAME,
'1' AS RATE,
'' AS S3,
LEFT(convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 101),5)+ ' 加值手續費-' + B.MERCHANT_NOTE AS MERCHANT_NOTE
FROM @NCC_TRT_FILED A
JOIN GM_MERCHANT_ACT B
ON A.MERCHANT_NO = B.MERCHANT_NO
JOIN GM_MERCHANT_ACT_TRT C
ON C.MERCHANT_NO = '84894989'

WHERE CPT_DATE = @CPT_DATE 
AND A.L_FEE <> 0 











--------------------
---北捷後送回饋金---
--------------------
INSERT INTO @TOTAL 
SELECT 'E' AS TITLE,
convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
'W'+RIGHT(A.CPT_DATE,6)+@NO1 AS NO1,
@NO2 AS NO2,
'0000' AS ROWID,
'117801' AS ACC_NO,
'' AS S1,
'D' AS ACC_CODE ,
SUM(REWARD_AMT) AS NET_AMT,
'84894989' AS MERCHANT_ACT,
'' AS S2,
'NT$' AS DOLLAR_NAME,
'1' AS RATE,
'' AS S3,
LEFT(convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 101),5)+ ' ' + '後送回饋金-北捷' AS MERCHANT_NOTE
FROM GM_TRT_REWARD_VIEW A
WHERE CPT_DATE = @CPT_DATE
GROUP BY CPT_DATE

UNION ALL

SELECT 'E' AS TITLE,
convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
'W'+RIGHT(A.CPT_DATE,6)+@NO1 AS NO1,
@NO2 AS NO2,
'0000' AS ROWID,
'282204' AS ACC_NO,
'' AS S1,
'C' AS ACC_CODE ,
SUM(REWARD_AMT) AS NET_AMT,
'84894989' AS MERCHANT_ACT,
'' AS S2,
'NT$' AS DOLLAR_NAME,
'1' AS RATE,
'' AS S3,
LEFT(convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 101),5)+ ' ' + '後送回饋金-北捷' AS MERCHANT_NOTE
FROM GM_TRT_REWARD_VIEW A
WHERE CPT_DATE = @CPT_DATE
GROUP BY CPT_DATE

--超商無人店扣薪加值 --20200525加入


INSERT INTO @TOTAL
SELECT 'E' AS TITLE,
		convert(varchar, dateadd(day,-1,convert(date,@CPT_DATE,112)), 112) AS BUSINESS_DATE,
		'W'+RIGHT(@CPT_DATE,6)+@NO1 AS NO1,
		@NO2,
		'0000' AS ROWID,
		'118802',
		'' AS S1,
		'D' AS ACC_CODE ,
		ISNULL(SUM(ISNULL(convert(int,TRANS_AMT),0)),0)  as NET_AMT,
		'22555003' AS MERCHANT_NO_ACT,
		'' AS S2,
		'NT$' AS DOLLAR_NAME,
		'1' AS RATE,
		'' AS S3,
		LEFT(convert(varchar, dateadd(day,-1,convert(date,@CPT_DATE,112)), 101),5)+' 無人店扣薪' AS MERCHANT_NOTE
		from isettle2.dbo.IM_OL_TXLOG_T_ICASH3 A
			inner join isettle2.dbo.CC_REGISTER_ICASH3 B on A.ICC_NO = B.CARD_NO
			where MERCHANT_NO = '22555003'
			and TRANS_TYPE = '22' 
			and FILE_TRANS_TYPE = '78' 
			and ZIP_FILE_NAME >= 'ICASH3_'+convert(varchar, dateadd(day,-1,convert(date,@CPT_DATE,112)), 112) +'000000'
			and ZIP_FILE_NAME <= 'ICASH3_'+convert(varchar, dateadd(day,-1,convert(date,@CPT_DATE,112)), 112)+'235959'
			and RETURN_CODE = '00000000'
		HAVING ISNULL(SUM(ISNULL(convert(int,TRANS_AMT),0)),0) > 0
--振興改科目

UPDATE @TOTAL
SET ACC_NO = '128191'
WHERE MERCHANT_NO_ACT = '04193850'




SELECT 
TITLE,
BUSINESS_DATE,
NO1,
NO2,
RIGHT('0000'+CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY MERCHANT_NO_ACT,ABS(NET_AMT))),4) AS ROWID,
ACC_NO,
S1,
ACC_CODE ,
ABS(NET_AMT),
MERCHANT_NO_ACT,
S2,
DOLLAR_NAME,
RATE,
S3,
MERCHANT_NOTE,
'' TEMP_AREA
FROM @TOTAL