SELECT 
	
	RIGHT('0000'+CONVERT(VARCHAR,DENSE_RANK()OVER(ORDER BY MERCHANT_NO_ACT_M)),4) AS ROWID,
	MONTH_DAY ,
	MERCHANT_NO_ACT_M ,
	CONVERT(BIGINT,ROUND(DIS_FEE_1,0)) as DIS_FEE_1,
	CONVERT(BIGINT,ROUND(FEE_AMT_1,0)) as FEE_AMT_1,
	EX_REC_DATE ,
	INVOICE_NO ,
	NAGITIVE_NUM ,
	TYPE_NUM ,
	CONVERT(BIGINT,ROUND(DIS_FEE_2,0)) as DIS_FEE_2,
	CONVERT(BIGINT,ROUND(FEE_AMT_2,0)) as FEE_AMT_2,
	NAME_1 ,
	ACCOUNTING ,
	DEPARTMENT ,
	EX_PAY_DATE,
	PROJECT_NO ,
	FREE_SPACE ,
	B2C_NUM ,
	CNT,
	SNO
FROM GM_MERCHANT_ACT_DATA_TEMP
WHERE MERCHANT_NO_ACT_M IN ( 
	SELECT DISTINCT A.MERCHANT_NO_ACT_M FROM GM_MERCHANT_ACT A
	JOIN GM_CONTRACT_M B
	ON A.MERCHANT_NO = B.MERCHANT_NO 
	WHERE SUM_DAY_S = CASE WHEN @DATE_RANGE = 'ALL' THEN SUM_DAY_S ELSE @DATE_RANGE END )
--AND MERCHANT_NO_ACT_M IN (SELECT DISTINCT MERCHANT_NO_ACT_M FROM GM_MERCHANT_ACT WHERE INVOICE_RULE = 'Y')
ORDER BY ROW_ID,RANK_ORDER