--DECLARE @CPT_DATE VARCHAR(8) = '20200102'
--DECLARE @NO1 VARCHAR(3) = '001' --
--DECLARE @NO2 VARCHAR(4) = '0010' --


--DECLARE @SCHEMAID VARCHAR(4)  = 'NCCC'
--DECLARE @AB_MERCHANT_NO VARCHAR(50) = '01508949'


DECLARE @TOTAL TABLE 
	(TITLE VARCHAR(2),
	BUSINESS_DATE VARCHAR(8),
	NO1 VARCHAR(15),
	NO2 VARCHAR(4),
	ROWID VARCHAR(4),
	ACC_NO VARCHAR(20),
	S1 VARCHAR(1),
	ACC_CODE VARCHAR(2),
	NET_AMT VARCHAR(15),
	MERCHANT_NO_ACT VARCHAR(50),
	S2 VARCHAR(1),
	DOLLAR_NAME VARCHAR(10),
	RATE VARCHAR(10),
	S3 VARCHAR(1),
	MERCHANT_NOTE VARCHAR(100))

	--SELECT B.MERCH_SCHEMAID, A.MERCHANT_NO FROM GM_OUTSOURING_GROUP A JOIN GM_MERCHANT B
	--ON A.MERCHANT_NO = B.MERCHANT_NO 



DECLARE @SCHEMAID VARCHAR(4) 
DECLARE @AB_MERCHANT_NO VARCHAR(50)
DECLARE A CURSOR FOR
SELECT M.MERCH_SCHEMAID,G.MERCHANT_NO 
FROM dbo.GM_OUTSOURING_GROUP G
inner join dbo.GM_MERCHANT M
	on G.MERCHANT_NO = M.MERCHANT_NO
OPEN A
FETCH NEXT FROM A INTO @SCHEMAID,@AB_MERCHANT_NO
WHILE @@FETCH_STATUS = 0
BEGIN

INSERT INTO @TOTAL

EXEC ('

SELECT ''A'' AS TITLE,
convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
''W''+RIGHT(A.CPT_DATE,6)+'''+@NO1+''' AS NO1,
'''+@NO2+''' AS NO2,
RIGHT(''0000''+CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY MERCHANT_NO_ACT_M)),4) AS ROWID,
CASE WHEN SUM(CONVERT(NUMERIC(10,0),FEE_AMT)) >0 THEN ''114305'' ELSE ''228105'' END   AS ACC_NO,
'''' AS S1,
''D'' AS ACC_CODE ,
SUM(CONVERT(NUMERIC(10,0),FEE_AMT)) AS NET_AMT,
merchant_no_act_m,
'''' AS S2,
''NT$'' AS DOLLAR_NAME,
''1'' AS RATE,
'''' AS S3,
REPLACE( ''消費手續費 '' + merchant_stname,''消費手續費 ***'',''***消費手續費 '') AS MERCHANT_NOTE

FROM
--SELECT merchant_no_act_m,merchant_stname,SUM(購貨淨額) FROM (
(SELECT CPT_DATE ,
REPLACE(g.MERCHANT_NAME,'' '','''') MERCHANT_NAME,
--ISNULL(ga.merchant_stname,''***''+g.MERCHANT_STNAME) merchant_stname,
CASE WHEN MERCHANT_NO_ACT IS NULL THEN ''***''+g.MERCHANT_STNAME 
WHEN GA.MERCHANT_STNAME IS NULL THEN g.MERCHANT_STNAME 
ELSE GA.MERCHANT_STNAME END AS merchant_stname,
ISNULL(ga.merchant_no_act_m,'''') merchant_no_act_m,
 g.MERCHANT_NO,
TRANS_AMT ,
FEE_RATE * 100 FEE_RATE,
dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC) FEE_AMT,
TRANS_AMT-dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC) PAY_NET,
REMITTANCE_DATE
FROM '+@SCHEMAID+'.TM_FEE_TYPE_DATA_D a JOIN GM_MERCHANT g
ON a.MERCHANT_NO = g.MERCHANT_NO
LEFT JOIN GM_MERCHANT_ACT ga
ON a.MERCHANT_NO = ga.merchant_no
WHERE CONTRACT_TYPE = ''P1'' AND FEE_CAL_FLG = ''AM'' AND FEE_KIND = ''CM''
AND a.MERCHANT_NO <> '''+ @AB_MERCHANT_NO +'''
AND ga.REM_TYPE IN (''A004'',''C001'') AND ga.SETTLE_RULE = ''D''
--AND a.MERCHANT_NO in (SELECT MERCHANT_NO FROM GM_REM_FEE_M WHERE CONTRACT_TYPE = ''P1'' AND REM_TYPE IN (''D'',''W''))
AND CPT_DATE = '''+@CPT_DATE+'''
) A
GROUP BY CPT_DATE,merchant_no_act_m ,merchant_stname
union all 
SELECT ''A'' AS TITLE,
convert(varchar, dateadd(day,-1,convert(date,CPT_DATE,112)), 112) AS BUSINESS_DATE,
''W''+RIGHT(A.CPT_DATE,6)+'''+@NO1+''' AS NO1,
'''+@NO2+''' AS NO2,
RIGHT(''0000''+CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY MERCHANT_NO_ACT_M)),4) AS ROWID,
CASE WHEN SUM(CONVERT(NUMERIC(10,0),FEE_AMT)) >0 THEN''228105'' ELSE ''214308'' END  AS ACC_NO,
'''' AS S1,
''C'' AS ACC_CODE ,
SUM(CONVERT(NUMERIC(10,0),FEE_AMT)) AS NET_AMT,
merchant_no_act_m,
'''' AS S2,
''NT$'' AS DOLLAR_NAME,
''1'' AS RATE,
'''' AS S3,
REPLACE( ''消費手續費 '' + merchant_stname,''消費手續費 ***'',''***消費手續費 '')  AS MERCHANT_NOTE

FROM
--SELECT merchant_no_act_m,merchant_stname,SUM(購貨淨額) FROM (
(SELECT CPT_DATE ,
REPLACE(g.MERCHANT_NAME,'' '','''') MERCHANT_NAME,
--ISNULL(ga.merchant_stname,''***''+g.MERCHANT_STNAME) merchant_stname,
CASE WHEN MERCHANT_NO_ACT IS NULL THEN ''***''+g.MERCHANT_STNAME 
WHEN GA.MERCHANT_STNAME IS NULL THEN g.MERCHANT_STNAME 
ELSE GA.MERCHANT_STNAME END AS merchant_stname,
ISNULL(ga.merchant_no_act_m,'''') merchant_no_act_m,
 g.MERCHANT_NO,
TRANS_AMT ,
FEE_RATE * 100 FEE_RATE,
dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC) FEE_AMT,
TRANS_AMT-dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC) PAY_NET,
REMITTANCE_DATE
FROM '+@SCHEMAID+'.TM_FEE_TYPE_DATA_D a JOIN GM_MERCHANT g
ON a.MERCHANT_NO = g.MERCHANT_NO
LEFT JOIN GM_MERCHANT_ACT ga
ON a.MERCHANT_NO = ga.merchant_no
WHERE CONTRACT_TYPE = ''P1'' AND FEE_CAL_FLG = ''AM'' AND FEE_KIND = ''CM''
AND a.MERCHANT_NO <> '''+ @AB_MERCHANT_NO +'''
AND ga.REM_TYPE IN (''A004'',''C001'') AND ga.SETTLE_RULE = ''D''
--AND a.MERCHANT_NO in (SELECT MERCHANT_NO FROM GM_REM_FEE_M WHERE CONTRACT_TYPE = ''P1'' AND REM_TYPE IN (''D'',''W''))
AND CPT_DATE = '''+@CPT_DATE+'''
) A
GROUP BY CPT_DATE,merchant_no_act_m ,merchant_stname

')
  FETCH NEXT FROM A INTO @SCHEMAID,@AB_MERCHANT_NO
END
CLOSE A
DEALLOCATE A

SELECT 
TITLE,
BUSINESS_DATE,
NO1,
NO2,
RIGHT('0000'+CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY MERCHANT_NO_ACT,MERCHANT_NOTE,ACC_CODE,ABS(NET_AMT))),4) AS ROWID,
ACC_NO,
S1,
ACC_CODE ,
ABS(NET_AMT),
MERCHANT_NO_ACT,
S2,
DOLLAR_NAME,
RATE,
S3,
MERCHANT_NOTE,
'' TEMP_AREA
FROM @TOTAL
WHERE NET_AMT <> 0