SELECT CONVERT(varchar(8), DATEADD(DAY,-1, a.CPT_DATE),112) CPT_DATE2, a.NAME, 		
		ISNULL(a.CM_AMT,0) AS CM_AMT,ISNULL(a.HM_AMT,0) AS HM_AMT, ISNULL(a.UT_AMT,0) AS UT_AMT,ISNULL(a.UT3_AMT,0) AS UT3_AMT,b.NAME AS R_NAME,ISNULL(b.CM_AMT,0) AS CMR_AMT,ISNULL(b.HM_AMT,0) AS HMR_AMT,ISNULL(b.UT_AMT,0) AS UTR_AMT,ISNULL(b.UT3_AMT,0) AS UT3R_AMT
FROM 
(
select  CPT_DATE, 'ÁÊ³f' AS NAME, 		
		SUM(CM_AMT) CM_AMT, SUM(HM_AMT) HM_AMT, SUM(UT_AMT) UT_AMT,SUM(UT3_AMT) UT3_AMT
from AM_ISET_MERC_TRANS_UTLOG_D		
where CPT_DATE between @sDate and @eDate		
and SRC_FLG = 'POS' and MERCHANT_NO = '22555003'	
and TRANS_TYPE = '21'	
group by CPT_DATE, TRANS_TYPE
) a
LEFT OUTER JOIN 
(
select 'ÁÊ³f¨ú®ø' AS NAME , 		
		SUM(CM_AMT) CM_AMT, SUM(HM_AMT) HM_AMT, SUM(UT_AMT) UT_AMT,SUM(UT3_AMT) UT3_AMT,CPT_DATE
from AM_ISET_MERC_TRANS_UTLOG_D		
where CPT_DATE between @sDate and @eDate		
and SRC_FLG = 'POS' and MERCHANT_NO = '22555003'	
and TRANS_TYPE = '23'	
group by CPT_DATE, TRANS_TYPE
) b
ON a.CPT_DATE=b.CPT_DATE
ORDER BY CPT_DATE2