---------玉山代收
DECLARE @MERC_TYPE VARCHAR(10);
SELECT @MERC_TYPE = MERCHANT_TYPE
FROM GM_MERCHANT
WHERE MERCHANT_NO = '{1}'

IF @MERC_TYPE = 'MUTI_MERC'
BEGIN 
SELECT 'SELECT	''{2}'' AS MERCHANT_NAME,	
        LEFT(a.trans_date_txlog,8) AS TRANS_DATE,	'+SELECTED_COLUMNS+
        ' AS TRANS_DESC ,COUNT(1) COUNT_NO , SUM(a.TRANS_AMT) AS SUM_AMT
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SETTLE_DATA_D a ' ELSE SERVER_NAME+'.{0}.TM_SETTLE_DATA_D a ' END 
+'left join GM_MERCHANT s '
+'on a.MERCHANT_NO = s.MERCHANT_NO
left join '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+' on a.TRANS_TYPE = b.TRANS_TYPE and a.MERCHANT_NO = b.MERCHANT_NO
WHERE a.trans_type=b.trans_type 
and b.SETTLE_FLG=''1'' AND a.CPT_DATE=@settleDate AND A.MERCHANT_NO = ''{1}''
GROUP BY LEFT(a.trans_date_txlog,8),'
+SELECTED_COLUMNS+
' 
ORDER BY 1,2,3,4,5'
AS SQL FROM GM_COMMON_M WHERE MERCHANT_NO='{1}' AND TYPE_GROUP='TRANS_DESC1'
END
--統聯、汎航
ELSE IF '{0}'  IN ('UBS','T02')
BEGIN
SELECT 'SELECT	''{2}'' AS MERCHANT_NAME,	
        LEFT(a.trans_date,8) AS TRANS_DATE,	'+SELECTED_COLUMNS+
        ' AS TRANS_DESC ,COUNT(1) COUNT_NO , SUM(a.TRANS_AMT) AS SUM_AMT
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SETTLE_DATA_D a ' ELSE SERVER_NAME+'.{0}.TM_SETTLE_DATA_D a ' END 
+'left join GM_MERCHANT s '
+'on a.MERCHANT_NO = s.MERCHANT_NO
left join '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+' on a.TRANS_TYPE = b.TRANS_TYPE 
WHERE a.trans_type=b.trans_type 
and b.SETTLE_FLG=''1'' AND a.CPT_DATE=@settleDate AND A.MERCHANT_NO = ''{1}''
GROUP BY LEFT(a.trans_date,8),'
+SELECTED_COLUMNS+
' 
ORDER BY 1,2,3,4,5'
AS SQL FROM GM_COMMON_M WHERE MERCHANT_NO='{1}' AND TYPE_GROUP='TRANS_DESC1'
END
--葛瑪蘭
ELSE IF '{0}' = 'KML'
BEGIN
SELECT 'SELECT	''{2}'' AS MERCHANT_NAME,	
        LEFT(a.trans_date,8) AS TRANS_DATE,	'+SELECTED_COLUMNS+
        ' AS TRANS_DESC ,COUNT(1) COUNT_NO , SUM(a.TRANS_AMT) AS SUM_AMT
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SETTLE_DATA_D a ' ELSE SERVER_NAME+'.{0}.TM_SETTLE_DATA_D a ' END 
+'left join GM_MERCHANT s '
+'on a.MERCHANT_NO = s.MERCHANT_NO
left join '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+' on a.TRANS_TYPE = b.TRANS_TYPE 
WHERE a.trans_type=b.trans_type 
and b.SETTLE_FLG=''1'' AND a.CPT_DATE=@settleDate AND A.MERCHANT_NO = ''{1}''
GROUP BY LEFT(a.trans_date,8),'
+SELECTED_COLUMNS+
'
UNION ALL 
SELECT	''{2}'' AS MERCHANT_NAME,	
        LEFT(a.trans_date_txlog,8) AS TRANS_DATE,	'+SELECTED_COLUMNS+
        ' AS TRANS_DESC ,COUNT(1) COUNT_NO , SUM(a.TRANS_AMT) AS SUM_AMT
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SETTLE_STATION_DATA_D a ' ELSE SERVER_NAME+'.{0}.TM_SETTLE_STATION_DATA_D a ' END 
+'left join GM_MERCHANT s '
+'on a.MERCHANT_NO = s.MERCHANT_NO
left join '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+' on a.TRANS_TYPE = b.TRANS_TYPE 
WHERE a.trans_type=b.trans_type 
and b.SETTLE_FLG=''1'' AND a.CPT_DATE=@settleDate AND A.MERCHANT_NO = ''{1}''
GROUP BY LEFT(a.trans_date_txlog,8),'
+SELECTED_COLUMNS+
' 
ORDER BY 1,2,3,4,5'
AS SQL FROM GM_COMMON_M WHERE MERCHANT_NO='{1}' AND TYPE_GROUP='TRANS_DESC1'
END
--其他特約機構
ELSE 
BEGIN
SELECT 'SELECT	''{2}'' AS MERCHANT_NAME,	
        LEFT(a.trans_date_txlog,8) AS TRANS_DATE,	'+SELECTED_COLUMNS+
        ' AS TRANS_DESC ,COUNT(1) COUNT_NO , SUM(a.TRANS_AMT) AS SUM_AMT
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SETTLE_DATA_D a ' ELSE SERVER_NAME+'.{0}.TM_SETTLE_DATA_D a ' END 
+'left join GM_MERCHANT s '
+'on a.MERCHANT_NO = s.MERCHANT_NO
left join '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+' on a.TRANS_TYPE = b.TRANS_TYPE 
WHERE a.trans_type=b.trans_type 
and b.SETTLE_FLG=''1'' AND a.CPT_DATE=@settleDate AND A.MERCHANT_NO = ''{1}''
GROUP BY LEFT(a.trans_date_txlog,8),'
+SELECTED_COLUMNS+
' 
ORDER BY 1,2,3,4,5'
AS SQL FROM GM_COMMON_M WHERE MERCHANT_NO='{1}' AND TYPE_GROUP='TRANS_DESC1'
END

