--------------------------------
--DECLARE @firstDate VARCHAR(8) = '20180301'
--DECLARE @EXEC_MERCHANT_NO VARCHAR(8) = '33846205'
DECLARE @EXEC_SDATE VARCHAR(8)
DECLARE @EXEC_EDATE VARCHAR(8)
-------帶入first_date，然後加1個月 用GM_CONTRACT_M找出日期區間
SELECT @EXEC_SDATE = GET_SUM_DATE.SDATE,
	   @EXEC_EDATE = GET_SUM_DATE.EDATE
FROM
(
	SELECT
		CASE WHEN SUM_DAY_S = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1				, DATEADD(MONTH, DATEDIFF(MONTH, '', convert(varchar(8), DATEADD(month, 1, @firstDate), 112)) + (SUM_MON_S + 1), '')), 112)
								   ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + SUM_DAY_S	, DATEADD(MONTH, DATEDIFF(MONTH, '', convert(varchar(8), DATEADD(month, 1, @firstDate), 112)) + (SUM_MON_S + 0), '')), 112) END AS 'SDATE',
		CASE WHEN SUM_DAY_E = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1				, DATEADD(MONTH, DATEDIFF(MONTH, '', convert(varchar(8), DATEADD(month, 1, @firstDate), 112)) + (SUM_MON_E + 1), '')), 112)
								   ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + SUM_DAY_E	, DATEADD(MONTH, DATEDIFF(MONTH, '', convert(varchar(8), DATEADD(month, 1, @firstDate), 112)) + (SUM_MON_E + 0), '')), 112) END AS 'EDATE'
		,SUM_DAY_S,SUM_DAY_E
	FROM	GM_CONTRACT_M
	WHERE	MERCHANT_NO = @EXEC_MERCHANT_NO
		AND	convert(varchar(8), DATEADD(month, 1, @firstDate), 112) BETWEEN EFF_DATE_FROM AND EFF_DATE_TO
)GET_SUM_DATE
--SELECT @EXEC_SDATE,@EXEC_EDATE
SELECT CPT_DATE,c.MERCHANT_NAME,b.TR_SYSTEM_NAME,d.TRANS_DESC,SUM(TRANS_AMT) AS SUM_AMT FROM icashbatchdb.itrans.[{0}].TM_SETTLE_DATA_D a
LEFT JOIN icashbatchdb.itrans.dbo.GM_TR_SYSTEM_M b
on a.TR_SYSTEM_ID = b.TR_SYSTEM_ID
LEFT JOIN GM_MERCHANT c
on a.MERCHANT_NO = c.MERCHANT_NO
LEFT JOIN icashbatchdb.itrans.[{0}].BM_TRANS_TYPE d
on a.TRANS_TYPE = d.TRANS_TYPE
WHERE CPT_DATE BETWEEN @EXEC_SDATE and @EXEC_EDATE
AND A.TRANS_TYPE IN ('22','23')
GROUP BY CPT_DATE,c.MERCHANT_NAME,b.TR_SYSTEM_NAME,d.TRANS_DESC
ORDER BY CPT_DATE