--DECLARE @sDate VARCHAR(8) = '20210801'
DECLARE @EXEC_MERCHANT_NO VARCHAR(8) = '07524729'
       ,@EXEC_SDATE VARCHAR(8)
       ,@EXEC_EDATE VARCHAR(8)
	   ,@FEE_RATE_P1 float
	   ,@FEE_RATE_L1 float
	   ,@FEE_RATE_L3 float
	   ,@FEE_RATE_L4 float

-------帶入first_date，用GM_CONTRACT_M找出日期區間
SELECT @EXEC_SDATE = GET_SUM_DATE.SDATE,
	   @EXEC_EDATE = GET_SUM_DATE.EDATE
FROM
(
	SELECT
		CASE WHEN SUM_DAY_S = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1				, DATEADD(MONTH, DATEDIFF(MONTH, '', convert(varchar(8), DATEADD(month, 1, @sDate), 112)) + (SUM_MON_S + 1), '')), 112)
								   ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + SUM_DAY_S	, DATEADD(MONTH, DATEDIFF(MONTH, '', convert(varchar(8), DATEADD(month, 1, @sDate), 112)) + (SUM_MON_S + 0), '')), 112) END AS 'SDATE',
		CASE WHEN SUM_DAY_E = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1				, DATEADD(MONTH, DATEDIFF(MONTH, '', convert(varchar(8), DATEADD(month, 1, @sDate), 112)) + (SUM_MON_E + 1), '')), 112)
								   ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + SUM_DAY_E	, DATEADD(MONTH, DATEDIFF(MONTH, '', convert(varchar(8), DATEADD(month, 1, @sDate), 112)) + (SUM_MON_E + 0), '')), 112) END AS 'EDATE'
		,SUM_DAY_S,SUM_DAY_E
	FROM	GM_CONTRACT_M
	WHERE	MERCHANT_NO = @EXEC_MERCHANT_NO
		AND	@sDate BETWEEN EFF_DATE_FROM AND EFF_DATE_TO
)GET_SUM_DATE

-------取得手續費率
SELECT @FEE_RATE_P1=MAX(CASE CONTRACT_TYPE WHEN 'P1' THEN FEE_RATE ELSE 0 END)
	,@FEE_RATE_L1=MAX(CASE CONTRACT_TYPE WHEN 'L1' THEN FEE_RATE ELSE 0 END)
	,@FEE_RATE_L3=MAX(CASE CONTRACT_TYPE WHEN 'L3' THEN FEE_RATE ELSE 0 END)
	,@FEE_RATE_L4=MAX(CASE CONTRACT_TYPE WHEN 'L4' THEN FEE_RATE ELSE 0 END)
FROM iSettle2.dbo.GM_CONTRACT_TR_D
WHERE MERCHANT_NO = @EXEC_MERCHANT_NO
	AND RANK_S = 1
	AND CONTRACT_TYPE IN ('P1','L1','L3','L4')
	AND @sDate BETWEEN EFF_DATE_FROM AND EFF_DATE_TO


SELECT D.MERCHANT_NO
	,D.CPT_DATE
	,D.TRANS_SUM_DATE
	,SUM(CASE WHEN B.CONTRACT_TYPE='P1' AND B.SETTLE_SIGN=1 THEN D.TRANS_AMT ELSE 0 END) [P1_PUR_AMT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='P1' AND B.SETTLE_SIGN=1 THEN D.TRANS_NONZERO_CNT ELSE 0 END) [P1_PUR_NONZERO_CNT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='P1' AND B.SETTLE_SIGN=(-1) THEN D.TRANS_AMT ELSE 0 END) [P1_PURR_AMT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='P1' AND B.SETTLE_SIGN=(-1) THEN D.TRANS_NONZERO_CNT ELSE 0 END) [P1_PURR_NONZERO_CNT]
	,@FEE_RATE_P1 [P1_FEE_RATE]

	,SUM(CASE WHEN B.CONTRACT_TYPE='L1' AND B.SETTLE_SIGN=1 THEN D.TRANS_AMT ELSE 0 END) [L1_LOAD_AMT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='L1' AND B.SETTLE_SIGN=1 THEN D.TRANS_NONZERO_CNT ELSE 0 END) [L1_LOAD_NONZERO_CNT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='L1' AND B.SETTLE_SIGN=(-1) THEN D.TRANS_AMT ELSE 0 END) [L1_LOADR_AMT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='L1' AND B.SETTLE_SIGN=(-1) THEN D.TRANS_NONZERO_CNT ELSE 0 END) [L1_LOADR_NONZERO_CNT]
	,@FEE_RATE_L1 [L1_FEE_RATE]

	,SUM(CASE WHEN B.CONTRACT_TYPE='L3' AND B.SETTLE_SIGN=1 THEN D.TRANS_AMT ELSE 0 END) [L3_LOAD_AMT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='L3' AND B.SETTLE_SIGN=1 THEN D.TRANS_NONZERO_CNT ELSE 0 END) [L3_LOAD_NONZERO_CNT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='L3' AND B.SETTLE_SIGN=(-1) THEN D.TRANS_AMT ELSE 0 END) [L3_LOADR_AMT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='L3' AND B.SETTLE_SIGN=(-1) THEN D.TRANS_NONZERO_CNT ELSE 0 END) [L3_LOADR_NONZERO_CNT]
	,@FEE_RATE_L3 [L3_FEE_RATE]

	,SUM(CASE WHEN B.CONTRACT_TYPE='L4' AND B.SETTLE_SIGN=1 THEN D.TRANS_AMT ELSE 0 END) [L4_LOAD_AMT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='L4' AND B.SETTLE_SIGN=1 THEN D.TRANS_NONZERO_CNT ELSE 0 END) [L4_LOAD_NONZERO_CNT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='L4' AND B.SETTLE_SIGN=(-1) THEN D.TRANS_AMT ELSE 0 END) [L4_LOADR_AMT]
	,SUM(CASE WHEN B.CONTRACT_TYPE='L4' AND B.SETTLE_SIGN=(-1) THEN D.TRANS_NONZERO_CNT ELSE 0 END) [L4_LOADR_NONZERO_CNT]
	,@FEE_RATE_L4 [L4_FEE_RATE]

	,SUM(CASE WHEN B.CONTRACT_TYPE IN ('L1','L3','L4') AND B.SETTLE_SIGN=1 THEN D.TRANS_AMT ELSE 0 END) [LOAD_TOTAL_AMT]
	,SUM(CASE WHEN B.CONTRACT_TYPE IN ('L1','L3','L4') AND B.SETTLE_SIGN=1 THEN D.TRANS_NONZERO_CNT ELSE 0 END) [LOAD_TOTAL_NONZERO_CNT]
	,SUM(CASE WHEN B.CONTRACT_TYPE IN ('L1','L3','L4') AND B.SETTLE_SIGN=(-1) THEN D.TRANS_AMT ELSE 0 END) [LOADR_TOTAL_AMT]
	,SUM(CASE WHEN B.CONTRACT_TYPE IN ('L1','L3','L4') AND B.SETTLE_SIGN=(-1) THEN D.TRANS_NONZERO_CNT ELSE 0 END) [LOADR_TOTAL_NONZERO_CNT]
FROM TRA.TM_TRANS_TR_SUM_D D
INNER JOIN TRA.BM_TRANS_TYPE B
	ON D.CPT_DATE between @EXEC_SDATE and @EXEC_EDATE
	AND B.CONTRACT_TYPE IN ('P1','L1','L3','L4')
	AND B.MERCHANT_NO = @EXEC_MERCHANT_NO
	AND D.TRANS_TYPE = B.TRANS_TYPE
	AND D.MERCHANT_NO = B.MERCHANT_NO
GROUP BY D.MERCHANT_NO, D.CPT_DATE, D.TRANS_SUM_DATE
ORDER BY CPT_DATE, TRANS_SUM_DATE
