SELECT 
--'SELECT	*  FROM GM_AMS_TEST 
--		WHERE MERCHANT_NO = ''{1}''
--		AND CPT_DATE BETWEEN ''{2}'' AND ''{3}''

--ORDER BY 1,2,3,4,5'
'SELECT D.CPT_DATE    ''清分日''
	,M.MERCHANT_NAME ''特約機構''
	,D.FILE_NAME     ''報表名稱''
	,''日報''          ''週期''
	,CASE WHEN D.CPT_SUCCESS=''Y''
		THEN ''成功''
		ELSE ''失敗''
	 END             ''清分結果''
	,CASE WHEN D.FILE_EXIST=''Y''
		THEN ''完整''
		ELSE ''缺漏''
	 END             ''群組檔案狀況''
	,CASE WHEN D.FILE_EXIST=''Y''
		THEN ''存在''
		ELSE ''不存在''
	 END             ''檔案存在''
	,D.FILE_AMT      ''報表金額''
	,CASE
		WHEN D.AMS_CHK_TYPE=''NET'' AND D.CPT_SUCCESS=''Y'' AND D.FILE_EXIST=''Y'' THEN CONVERT(VARCHAR, ISNULL((A.PCH_AMT-A.PCHR_AMT)-(A.LOAD_AMT-A.LOADR_AMT), 0) )
		WHEN D.AMS_CHK_TYPE=''P''   AND D.CPT_SUCCESS=''Y'' AND D.FILE_EXIST=''Y'' THEN CONVERT(VARCHAR, ISNULL(A.PCH_AMT-A.PCHR_AMT, 0) )
		WHEN D.AMS_CHK_TYPE=''L''   AND D.CPT_SUCCESS=''Y'' AND D.FILE_EXIST=''Y'' THEN CONVERT(VARCHAR, ISNULL(A.LOAD_AMT-A.LOADR_AMT, 0) )
		ELSE ''''
	 END             ''AMS金額''
	,CASE
		WHEN D.AMS_CHK_TYPE=''NET'' AND D.CPT_SUCCESS=''Y'' AND D.FILE_EXIST=''Y'' THEN CONVERT(VARCHAR, D.FILE_AMT-ISNULL((A.PCH_AMT-A.PCHR_AMT)-(A.LOAD_AMT-A.LOADR_AMT), 0) )
		WHEN D.AMS_CHK_TYPE=''P''   AND D.CPT_SUCCESS=''Y'' AND D.FILE_EXIST=''Y'' THEN CONVERT(VARCHAR, D.FILE_AMT-ISNULL(A.PCH_AMT-A.PCHR_AMT, 0) )
		WHEN D.AMS_CHK_TYPE=''L''   AND D.CPT_SUCCESS=''Y'' AND D.FILE_EXIST=''Y'' THEN CONVERT(VARCHAR, D.FILE_AMT-ISNULL(A.LOAD_AMT-A.LOADR_AMT, 0) )
		ELSE ''''
	 END             ''差異金額''
	,CASE WHEN D.FILE_EXIST=''Y''
		THEN ''審核中''
		ELSE ''未存在''
	 END             ''狀態''
	 , *
FROM iSettle2.dbo.GM_MAIL_DATA D
INNER JOIN iSettle2.dbo.GM_MERCHANT M
	ON D.MERCHANT_NO = M.MERCHANT_NO
LEFT JOIN iSettle2.dbo.AM_ISET_MERC_TRANS_LOG_D A
	ON D.MERCHANT_NO = A.MERCHANT_NO
	AND D.CPT_DATE = A.CPT_DATE
WHERE D.CPT_DATE BETWEEN @startDate AND @endDate
	AND D.MERCHANT_NO = @merchant
ORDER BY D.CPT_DATE,D.MERCHANT_NO

'
AS SQL 
