--DECLARE @EXEC_CPT_DATE VARCHAR(8) = '20191002'
DECLARE @EXEC_MERCHANT_NO VARCHAR(20) = '70810572'
DECLARE @RATE DECIMAL(15,5)
DECLARE @SDATE VARCHAR(8)
DECLARE @EDATE VARCHAR(8)


SELECT @SDATE = GET_SUM_DATE.SDATE,
        @EDATE = GET_SUM_DATE.EDATE
FROM
(
	SELECT
		CASE WHEN SUM_DAY_S = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1				, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_CPT_DATE) + (SUM_MON_S + 1), '')), 112)
								    ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + SUM_DAY_S	, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_CPT_DATE) + (SUM_MON_S + 0), '')), 112) END AS 'SDATE',
		CASE WHEN SUM_DAY_E = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1				, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_CPT_DATE) + (SUM_MON_E + 1), '')), 112)
								    ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + SUM_DAY_E	, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_CPT_DATE) + (SUM_MON_E + 0), '')), 112) END AS 'EDATE'
		,SUM_DAY_S,SUM_DAY_E
	FROM	GM_CONTRACT_M
	WHERE	MERCHANT_NO = @EXEC_MERCHANT_NO
		AND	@EXEC_CPT_DATE BETWEEN EFF_DATE_FROM AND EFF_DATE_TO
)GET_SUM_DATE

SELECT @SDATE,@EDATE
SELECT @RATE = FEE_RATE FROM GM_CONTRACT_TR_D WHERE MERCHANT_NO = @EXEC_MERCHANT_NO AND FEE_CAL_FLG = 'CT' AND CONTRACT_TYPE = 'P1'
SELECT @RATE

  SELECT LEFT(TRANS_DATE_TXLOG,8),'里程',COUNT(1),@RATE,COUNT(1) * @RATE FROM icashbatchdb.itrans.B116.TM_SETTLE_DATA_D
  WHERE CPT_DATE BETWEEN @SDATE AND @EDATE
  and (TR_KIND like '0_' or TR_KIND = '15') and TRANS_TYPE = '22'
  GROUP BY  LEFT(TRANS_DATE_TXLOG,8),TRANS_TYPE
  union all
  SELECT LEFT(TRANS_DATE_TXLOG,8),'段次',COUNT(1),@RATE,COUNT(1) * @RATE FROM icashbatchdb.itrans.B116.TM_SETTLE_DATA_D
  WHERE CPT_DATE BETWEEN @SDATE AND @EDATE
  and TR_KIND <> '10' and TRANS_TYPE = '23'
  GROUP BY  LEFT(TRANS_DATE_TXLOG,8),TRANS_TYPE
  UNION ALL
  SELECT '里程總計','',COUNT(1),@RATE,COUNT(1) * @RATE FROM icashbatchdb.itrans.B116.TM_SETTLE_DATA_D
  WHERE CPT_DATE BETWEEN @SDATE AND @EDATE
  and (TR_KIND like '0_' or TR_KIND = '15') and TRANS_TYPE = '22'
  UNION ALL
  SELECT '段次總計','',COUNT(1),@RATE,COUNT(1) * @RATE FROM icashbatchdb.itrans.B116.TM_SETTLE_DATA_D
  WHERE CPT_DATE BETWEEN @SDATE AND @EDATE
  and TR_KIND <> '10' and TRANS_TYPE = '23'
  UNION ALL
  SELECT '總計','',COUNT(1),@RATE,COUNT(1) * @RATE FROM icashbatchdb.itrans.B116.TM_SETTLE_DATA_D
  WHERE CPT_DATE BETWEEN @SDATE AND @EDATE
  and (((TR_KIND like '0_' or TR_KIND = '15') and TRANS_TYPE = '22') 
  OR (TR_KIND <> '10' and TRANS_TYPE = '23'))
  