DECLARE @MERC_TYPE VARCHAR(10);
SELECT @MERC_TYPE = MERCHANT_TYPE
FROM GM_MERCHANT
WHERE MERCHANT_NO = '{1}'

IF @MERC_TYPE = 'MUTI_MERC'
BEGIN
SELECT 'SELECT	''{2}'',a.CPT_DATE,
		a.STORE_NO,
		CASE WHEN S.STO_NAME_SHORT IS NULL
			THEN ''主檔已刪除''
			ELSE S.STO_NAME_SHORT
		END [STO_NAME_SHORT],
		a.REG_ID,		
        a.trans_date_txlog,	'+SELECTED_COLUMNS+
        ',a.TRANS_AMT,		
        a.REMITTANCE_DATE
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SETTLE_DATA_D a ' ELSE SERVER_NAME+'.{0}.TM_SETTLE_DATA_D a ' END 
+'left join '+CASE SERVER_NAME WHEN '' THEN '{0}.BM_STORE_M s ' ELSE SERVER_NAME+'.{0}.BM_STORE_M s ' END
+'on a.STORE_NO=s.STORE_NO AND a.MERCHANT_NO = s.MERCHANT_NO, '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+'WHERE 
a.trans_type=b.trans_type
and b.MERCHANT_NO = ''{1}'' and a.MERCHANT_NO = ''{1}''
and b.SETTLE_FLG=''1'' AND a.CPT_DATE between @sDate and @eDate
ORDER BY 1,2,3,4,5'
        AS SQL FROM GM_COMMON_M WHERE MERCHANT_NO='{1}' AND TYPE_GROUP='TRANS_DESC1'
END
ELSE IF '{0}' IN ('UBS','T02')
BEGIN
SELECT 'SELECT	''{2}'',a.CPT_DATE,
		a.ROUTE_NO AS STORE_NO,		
		CASE WHEN S.STO_NAME_SHORT IS NULL
			THEN ''主檔已刪除''
			ELSE S.STO_NAME_SHORT
		END [STO_NAME_SHORT],	 
		'''' REG_ID,		
        a.trans_date AS TRANS_DATE_TXLOG,	'+SELECTED_COLUMNS+
        ',a.TRANS_AMT,		
        a.REMITTANCE_DATE
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SETTLE_DATA_D a ' ELSE SERVER_NAME+'.{0}.TM_SETTLE_DATA_D a ' END 
+'left join '+CASE SERVER_NAME WHEN '' THEN '{0}.BM_STORE_M s ' ELSE SERVER_NAME+'.{0}.BM_STORE_M s ' END
+'on a.ROUTE_NO=s.STORE_NO AND a.MERCHANT_NO = s.MERCHANT_NO, '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+'WHERE 
a.trans_type=b.trans_type
and b.SETTLE_FLG=''1'' AND a.CPT_DATE between @sDate and @eDate
ORDER BY 1,2,3,4,5'
        AS SQL FROM GM_COMMON_M WHERE MERCHANT_NO='{1}' AND TYPE_GROUP='TRANS_DESC1'
END
ELSE IF '{0}' = 'KML'
BEGIN
SELECT 'SELECT	''{2}'',a.CPT_DATE,
		a.ROUTE_NO AS STORE_NO,		
		CASE WHEN S.STO_NAME_SHORT IS NULL
			THEN ''主檔已刪除''
			ELSE S.STO_NAME_SHORT
		END [STO_NAME_SHORT],	 
		'''' REG_ID,		
        a.trans_date AS TRANS_DATE_TXLOG,	'+SELECTED_COLUMNS+
        ',a.TRANS_AMT,		
        a.REMITTANCE_DATE
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SETTLE_DATA_D a ' ELSE SERVER_NAME+'.{0}.TM_SETTLE_DATA_D a ' END 
+'left join '+CASE SERVER_NAME WHEN '' THEN '{0}.BM_STORE_M s ' ELSE SERVER_NAME+'.{0}.BM_STORE_M s ' END
+'on a.ROUTE_NO=s.STORE_NO AND a.MERCHANT_NO = s.MERCHANT_NO, '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+'WHERE 
a.trans_type=b.trans_type
and b.SETTLE_FLG=''1'' AND a.CPT_DATE between @sDate and @eDate
UNION ALL ' +
'
SELECT	''{2}'',a.CPT_DATE,
		a.STORE_NO,		
		CASE WHEN S.STO_NAME_SHORT IS NULL
			THEN ''主檔已刪除''
			ELSE S.STO_NAME_SHORT
		END [STO_NAME_SHORT],	 
		a.REG_ID,		
        a.trans_date_txlog,	'+SELECTED_COLUMNS+
        ',a.TRANS_AMT,		
        a.REMITTANCE_DATE
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SETTLE_STATION_DATA_D a ' ELSE SERVER_NAME+'.{0}.TM_SETTLE_STATION_DATA_D a ' END 
+'left join '+CASE SERVER_NAME WHEN '' THEN '{0}.BM_STORE_M s ' ELSE SERVER_NAME+'.{0}.BM_STORE_M s ' END
+'on a.STORE_NO=s.STORE_NO AND a.MERCHANT_NO = s.MERCHANT_NO, '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+'WHERE 
a.trans_type=b.trans_type
and b.SETTLE_FLG=''1'' AND a.CPT_DATE between @sDate and @eDate
ORDER BY 1,2,3,4,5'
        AS SQL FROM GM_COMMON_M WHERE MERCHANT_NO='{1}' AND TYPE_GROUP='TRANS_DESC1'

END
ELSE
BEGIN
SELECT 'SELECT	''{2}'',a.CPT_DATE,
		a.STORE_NO,		
		CASE WHEN S.STO_NAME_SHORT IS NULL
			THEN ''主檔已刪除''
			ELSE S.STO_NAME_SHORT
		END [STO_NAME_SHORT],	 
		a.REG_ID,		
        a.trans_date_txlog,	'+SELECTED_COLUMNS+
        ',a.TRANS_AMT,		
        a.REMITTANCE_DATE
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SETTLE_DATA_D a ' ELSE SERVER_NAME+'.{0}.TM_SETTLE_DATA_D a ' END 
+'left join '+CASE SERVER_NAME WHEN '' THEN '{0}.BM_STORE_M s ' ELSE SERVER_NAME+'.{0}.BM_STORE_M s ' END
+'on a.STORE_NO=s.STORE_NO AND a.MERCHANT_NO = s.MERCHANT_NO, '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+'WHERE 
a.trans_type=b.trans_type
and b.SETTLE_FLG=''1'' AND a.CPT_DATE between @sDate and @eDate
ORDER BY 1,2,3,4,5'
        AS SQL FROM GM_COMMON_M WHERE MERCHANT_NO='{1}' AND TYPE_GROUP='TRANS_DESC1'
END