DECLARE @MERC_TYPE VARCHAR(10);
DECLARE @SERVER VARCHAR(30);
DECLARE @CNT INT;
SELECT @MERC_TYPE = MERCHANT_TYPE
FROM GM_MERCHANT
WHERE MERCHANT_NO = '{1}'

SELECT @SERVER = SERVER_NAME
FROM GM_COMMON_M
WHERE MERCHANT_NO = '{1}' AND TYPE_GROUP='TRANS_DESC1'

SELECT  @CNT = COUNT(1) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TM_SKIP_TXLOG_D' AND TABLE_SCHEMA = '{0}'
IF @CNT = 1 
BEGIN
SELECT 'SELECT	''{2}'' AS MERCHANT_NAME,a.CPT_DATE,
		a.STORE_NO,		
		s.STO_NAME_SHORT,
		a.ICC_NO,	 
		a.REG_ID,		
        a.trans_date_txlog,	'+SELECTED_COLUMNS+
        ' AS TRANS_DESC,a.TRANS_AMT,		
         a.DIFF_FLG,		
        d.DIFF_DESC,
		''SKIP_TX'' AS TABLE_NAME		
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_SKIP_TXLOG_D a ' ELSE SERVER_NAME+'.{0}.TM_SKIP_TXLOG_D a ' END 
+'left join '+CASE SERVER_NAME WHEN '' THEN '{0}.BM_DIFF_M d ' ELSE SERVER_NAME+'.{0}.BM_DIFF_M d ' END
+'on a.DIFF_FLG = d.DIFF_FLG '
+'left join '+CASE SERVER_NAME WHEN '' THEN '{0}.BM_STORE_M s ' ELSE SERVER_NAME+'.{0}.BM_STORE_M s ' END
+'on a.STORE_NO=s.STORE_NO, '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+'WHERE 
a.trans_type=b.trans_type
and b.SETTLE_FLG=''1'' AND a.TRANS_DATE_TXLOG like ''{4}%''
and a.ICC_NO = ''{3}''
ORDER BY 1,2,3,4,5'
        AS SQL FROM GM_COMMON_M WHERE MERCHANT_NO='{1}' AND TYPE_GROUP='TRANS_DESC1'
END
ELSE IF @MERC_TYPE = 'MUTI_MERC' OR @SERVER <> '' OR '{0}' IN ('UBS','T02','KML') OR @CNT = 0
BEGIN
SELECT 'SELECT	'''' AS MERCHANT_NAME,'''' AS CPT_DATE ,
		'''' AS STORE_NO,		
		'''' AS STO_NAME_SHORT,	
		'''' AS ICC_NO, 
		'''' AS REG_ID,		
        '''' AS trans_date_txlog,
		'''' AS TRANS_DESC,
		Null AS TRANS_AMT,
		'''' AS DIFF_FLG,		
        '''' AS DIFF_DESC,
		'''' AS TABLE_NAME	
			'
			AS SQL
END

