SELECT 
(SELECT ISNUlL(SUM(CM_AMT),0) from AM_ISET_MERC_TRANS_UTLOG_D		
where CPT_DATE between @EXEC_CPT_DATE_B and @EXEC_CPT_DATE_E		
and SRC_FLG = 'POS' and MERCHANT_NO = '22555003'	
and TRANS_TYPE = '21')
-
(SELECT ISNULL(SUM(CM_AMT),0) from AM_ISET_MERC_TRANS_UTLOG_D		
where CPT_DATE between @EXEC_CPT_DATE_B and @EXEC_CPT_DATE_E		
and SRC_FLG = 'POS' and MERCHANT_NO = '22555003'	
and TRANS_TYPE = '23')