
--DECLARE @SDATE VARCHAR(8) = '20190701'
--DECLARE @EDATE VARCHAR(8) = '20190831'


DECLARE @EXEC_MERCHANT_NO VARCHAR(20) = '90724553'
DECLARE @RATE decimal(15,5)

SELECT @RATE = FEE_RATE FROM GM_CONTRACT_TR_D
WHERE MERCHANT_NO = '90724553' and CONTRACT_TYPE  = 'P1' AND FEE_CAL_FLG = 'CT'

SELECT @RATE

SELECT LEFT(TRANS_DATE_TXLOG,6) AS YM ,SUM(TRANS_AMT) AS SUM_AMT,COUNT(1) AS CNT,@RATE AS FEE_RATE,COUNT(1) * @RATE AS FEE_AMT FROM icashbatchdb.itrans.B808.TM_SETTLE_DATA_D
WHERE CPT_DATE BETWEEN @SDATE AND @EDATE AND MERCHANT_NO = @EXEC_MERCHANT_NO
GROUP BY LEFT(TRANS_DATE_TXLOG,6)
ORDER BY 1

SELECT 'Á`­p' AS Total, SUM(TRANS_AMT) AS SUM_AMT,COUNT(1) AS CNT,@RATE FEE_RATE,COUNT(1) * @RATE AS FEE_AMT FROM  icashbatchdb.itrans.B808.TM_SETTLE_DATA_D
WHERE CPT_DATE BETWEEN @SDATE AND @EDATE AND MERCHANT_NO = @EXEC_MERCHANT_NO
ORDER BY 1

