--DECLARE @EXEC_MERCHANT_NO VARCHAR(8) = ''
--DECLARE @SDATE VARCHAR(8) = ''
--DECLARE @EDATE VARCHAR(8) = ''

--SELECT CPT_DATE AS '清分日',
--g.MERCHANT_NAME AS '特店名稱',
-- g.MERCHANT_NO AS '特店編號',
--TRANS_AMT AS '購貨淨額', 
--FEE_RATE * 100 AS '扣款手續費率',
--dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC) AS '扣款手續費',
--TRANS_AMT-dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC) AS '撥付淨額',
--REMITTANCE_DATE AS '撥付日期'
--FROM NCCC.TM_FEE_TYPE_DATA_D a JOIN GM_MERCHANT g
--ON a.MERCHANT_NO = g.MERCHANT_NO
--WHERE CONTRACT_TYPE = 'P1' AND FEE_CAL_FLG = 'AM' AND FEE_KIND = 'CM'
--AND a.MERCHANT_NO <> '01508949'
--AND a.MERCHANT_NO = @EXEC_MERCHANT_NO
--AND CPT_DATE BETWEEN @SDATE AND @EDATE
--ORDER BY CPT_DATE,a.MERCHANT_NO

--20200331變更
SELECT CPT_DATE AS '清分日',
g.MERCHANT_NAME AS '特店名稱',
 g.MERCHANT_NO AS '特店編號',
TRANS_AMT AS '購貨淨額', 
FEE_RATE * 100 AS '扣款手續費率',
dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC) AS '扣款手續費',
TRANS_AMT-dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC) AS '撥付淨額',
REMITTANCE_DATE AS '撥付日期'
FROM {0}.TM_FEE_TYPE_DATA_D a JOIN GM_MERCHANT g
ON a.MERCHANT_NO = g.MERCHANT_NO
WHERE CONTRACT_TYPE = 'P1' AND FEE_CAL_FLG = 'AM' AND FEE_KIND = 'CM'
AND a.MERCHANT_NO <> @AB_MERCHANT_NO 
AND a.MERCHANT_NO IN (SELECT MERCHANT_NO FROM GM_MERCHANT_ACT WHERE  REM_TYPE IN ('A004','C001') AND SETTLE_RULE = 'D')
--AND a.MERCHANT_NO = @EXEC_MERCHANT_NO
AND CPT_DATE BETWEEN @SDATE AND @EDATE 
ORDER BY CPT_DATE,a.MERCHANT_NO



--SELECT CPT_DATE '清分日',MERCHANT_STNAME '特店名稱',MERCHANT_NO_ACT_M '特店編號', SUM(TRANS_AMT) '購貨淨額',
--FEE_RATE '扣款手續費率',SUM(FEE_AMT) '扣款手續費',SUM(PAY_NET) '撥付淨額',REMITTANCE_DATE  '撥付日期'
--FROM (
--SELECT CPT_DATE ,
--g.MERCHANT_NAME ,
--g.MERCHANT_NO  ,
--ga.MERCHANT_NO_ACT_M,
--CASE WHEN MERCHANT_NO_ACT IS NULL THEN '***'+g.MERCHANT_STNAME 
--WHEN ga.MERCHANT_STNAME IS NULL THEN g.MERCHANT_STNAME 
--ELSE ga.MERCHANT_STNAME END AS merchant_stname,
--TRANS_AMT, 
--FEE_RATE * 100 FEE_RATE ,
--dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC)  FEE_AMT,
--TRANS_AMT-dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC)  PAY_NET ,
--REMITTANCE_DATE 
--FROM {0}.TM_FEE_TYPE_DATA_D a JOIN GM_MERCHANT g
--ON a.MERCHANT_NO = g.MERCHANT_NO
--LEFT JOIN GM_MERCHANT_ACT ga
--on a.MERCHANT_NO = ga.MERCHANT_NO
--WHERE CONTRACT_TYPE = 'P1' AND FEE_CAL_FLG = 'AM' AND FEE_KIND = 'CM'
--AND a.MERCHANT_NO <> @AB_MERCHANT_NO 
--AND REM_TYPE IN ('A004','C001') AND SETTLE_RULE = 'D'
----AND a.MERCHANT_NO = @EXEC_MERCHANT_NO
--AND CPT_DATE BETWEEN @SDATE AND @EDATE 
--) T
--GROUP BY CPT_DATE ,MERCHANT_NO_ACT_M ,MERCHANT_STNAME, FEE_RATE,REMITTANCE_DATE 
--ORDER BY CPT_DATE,MERCHANT_NO_ACT_M

