DECLARE @TmpDetail TABLE (
MERCHANT_NO varchar(20), 
MERCHANT_NAME varchar(20),
INVOICE_NO varchar(8),
CPT_DATE varchar(8),
BUSINESS_DATE varchar(8),
cal_item varchar(8),
cnt int,
FEE_RATE varchar(4)
)

DECLARE @EXEC_CPT_DATE VARCHAR(8) = '{1}'
DECLARE @EXEC_MERCHANT_NO VARCHAR(8) ='{2}'

DECLARE @SDATE VARCHAR(8)
DECLARE @EDATE VARCHAR(8)
SELECT @SDATE = GET_SUM_DATE.SDATE,
        @EDATE = GET_SUM_DATE.EDATE
FROM
(
	SELECT
		CASE WHEN SUM_DAY_S = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1				, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_CPT_DATE) + (SUM_MON_S + 1), '')), 112)
								    ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + SUM_DAY_S	, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_CPT_DATE) + (SUM_MON_S + 0), '')), 112) END AS 'SDATE',
		CASE WHEN SUM_DAY_E = '99' THEN CONVERT(VARCHAR(8), DATEADD(DAY, -1				, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_CPT_DATE) + (SUM_MON_E + 1), '')), 112)
								    ELSE CONVERT(VARCHAR(8), DATEADD(DAY, -1 + SUM_DAY_E	, DATEADD(MONTH, DATEDIFF(MONTH, '', @EXEC_CPT_DATE) + (SUM_MON_E + 0), '')), 112) END AS 'EDATE'
		,SUM_DAY_S,SUM_DAY_E
	FROM	GM_CONTRACT_M
	WHERE	MERCHANT_NO = @EXEC_MERCHANT_NO
		AND	@EXEC_CPT_DATE BETWEEN EFF_DATE_FROM AND EFF_DATE_TO
)GET_SUM_DATE



INSERT INTO @TmpDetail
SELECT MERCHANT_NO
    ,MERCHANT_NAME
	,INVOICE_NO
	, CPT_DATE
	, BUSINESS_DATE
	,cal_item
	, COUNT(1) as cnt
	,convert(varchar,convert(float,FEE_RATE))
FROM (
SELECT V.MERCHANT_NO
    , GM.MERCHANT_NAME
	,GM.INVOICE_NO
	, V.CPT_DATE
	, V.BUSINESS_DATE
	,'一日二段' as cal_item
	,C.FEE_RATE
FROM icashbatchdb.itrans.{0}.TM_SETTLE_DATA_D V
INNER JOIN icashbatchdb.itrans.{0}.BM_STORE_M BM ON V.STORE_NO = BM.STORE_NO
	AND V.MERCHANT_NO = BM.MERCHANT_NO
	AND BM.LINE_NO_04 = '03'	
inner join GM_MERCHANT GM on V.MERCHANT_NO=GM.MERCHANT_NO
inner join icashbatchdb.itrans.{0}.BM_TRANS_TYPE T    on V.TRANS_TYPE = T.TRANS_TYPE 
inner join dbo.GM_CONTRACT_TR_D C  on T.CONTRACT_TYPE = C.CONTRACT_TYPE and V.MERCHANT_NO = C.MERCHANT_NO and C.ISZERO = 'Y'
WHERE  V.CPT_DATE between @sDate and @eDate
  AND V.TR_METHOD = '11'
  AND V.TR_KIND = '00'
  AND V.FREE_AMT <> '0'
  AND V.MERCHANT_NO = @EXEC_MERCHANT_NO
UNION ALL
SELECT V.MERCHANT_NO
    , GM.MERCHANT_NAME
	,GM.INVOICE_NO
	, V.CPT_DATE
	, V.BUSINESS_DATE
	,'其他轉乘' as cal_item
	,C.FEE_RATE
FROM icashbatchdb.itrans.{0}.TM_SETTLE_DATA_D V
INNER JOIN icashbatchdb.itrans.{0}.BM_STORE_M BM ON V.STORE_NO = BM.STORE_NO 
    AND V.MERCHANT_NO = BM.MERCHANT_NO
	AND BM.LINE_NO_04 = '03'	
inner join GM_MERCHANT GM on V.MERCHANT_NO=GM.MERCHANT_NO
inner join icashbatchdb.itrans.{0}.BM_TRANS_TYPE T    on V.TRANS_TYPE = T.TRANS_TYPE 
inner join dbo.GM_CONTRACT_TR_D C  on T.CONTRACT_TYPE = C.CONTRACT_TYPE and V.MERCHANT_NO = C.MERCHANT_NO and C.ISZERO = 'Y'
WHERE V.CPT_DATE between @SDATE and @EDATE
  AND V.TR_METHOD = '11'
  AND V.TR_KIND = '00'
  AND V.TRANS_DISC_AMT <> '0' 
  AND V.TRANSFER_GROUP_CODE1 + V.TRANSFER_GROUP_CODE2 IN ('3233','3333','1233','0833')
  AND V.MERCHANT_NO = @EXEC_MERCHANT_NO
	) A	
GROUP BY MERCHANT_NO,MERCHANT_NAME,INVOICE_NO,CPT_DATE, BUSINESS_DATE,cal_item,FEE_RATE
ORDER BY MERCHANT_NO,MERCHANT_NAME,INVOICE_NO, CPT_DATE, BUSINESS_DATE,cal_item,FEE_RATE

select MERCHANT_NO, MERCHANT_NAME,INVOICE_NO ,CPT_DATE,BUSINESS_DATE ,cal_item ,cnt,FEE_RATE  
from @TmpDetail
order by MERCHANT_NO,CPT_DATE,BUSINESS_DATE,cal_item


