--序號	客戶代號(會計的)	特約機構	購貨金額	購貨手續費率	購貨手續費	未稅	稅金

--DECLARE @SDATE VARCHAR(8) = '20180601'
--DECLARE @EDATE VARCHAR(8) = '20180731'
--DECLARE @EXEC_MERCHANT_NO VARCHAR(8) = 'A0000002'



DECLARE @TEMP TABLE (	MERCHANT_NO varchar(10),
						MERCHANT_NAME varchar(50),
						NET_AMT NUMERIC(20,5),
						FEE_RATE NUMERIC(15,5),
						FEE_AMT NUMERIC(20,5),
						NFAX NUMERIC(20,5),
						FAX NUMERIC(20,5));
INSERT INTO @TEMP
SELECT A.MERCHANT_NO,MERCHANT_NAME,(SUM(PCH_AMT)-SUM(PCHR_AMT)) AS 'NET_AMT',
FEE_RATE * 100 AS 'FEE_RATE',(SUM(PCH_AMT)-SUM(PCHR_AMT)) * FEE_RATE AS 'FEE_AMT',
((SUM(PCH_AMT)-SUM(PCHR_AMT)) * FEE_RATE / 1.05) AS 'NFAX',
((SUM(PCH_AMT)-SUM(PCHR_AMT)) * FEE_RATE) - ((SUM(PCH_AMT)-SUM(PCHR_AMT)) * FEE_RATE / 1.05) AS 'FAX'
FROM AM_ISET_MERC_TRANS_LOG_D A
INNER JOIN GM_MERCHANT B
ON A.MERCHANT_NO = B.MERCHANT_NO
INNER JOIN GM_CONTRACT_MUTI_MERC_D C
ON A.MERCHANT_NO = C.MERCHANT_NO
INNER JOIN GM_MERCHANT_TYPE_D D
ON A.MERCHANT_NO = D.MERCHANT_NO
WHERE CPT_DATE BETWEEN @SDATE AND @EDATE
AND CPT_DATE BETWEEN EFF_DATE_FROM AND EFF_DATE_TO
AND CONTRACT_TYPE = 'P1' AND FEE_KIND = 'CM' AND FEE_CAL_FLG = 'AM' 
AND D.GROUP_ID = 'MSTORE'
--AND A.MERCHANT_NO = CASE WHEN @EXEC_MERCHANT_NO = 'ALL' THEN A.MERCHANT_NO ELSE @EXEC_MERCHANT_NO END
GROUP BY A.MERCHANT_NO,MERCHANT_NAME,FEE_RATE

SELECT	ROW_NUMBER() OVER(ORDER BY MERCHANT_NO) AS '序號',
		MERCHANT_NO AS '客戶代號',
		MERCHANT_NAME AS '特約機構',
		NET_AMT AS '購貨金額',
		FEE_RATE AS '購貨手續費率',
		FEE_AMT AS '購貨手續費',
		NFAX AS '未稅',FAX AS '稅金' FROM @TEMP