--SELECT A.CPT_DATE,A.CPT_MERCHANT_NO,MERCHANT_NAME,A.TRANS_CNT,A.CPT_AMT,A.FEE_RATE * 100,A.FEE_AMT ,

--ISNULL((SELECT B.CPT_AMT FROM NCCC.TM_FEE_TYPE_DATA_D B WHERE  B.CONTRACT_TYPE = 'L1' AND B.FEE_CAL_FLG = 'AM' AND B.FEE_KIND = 'CM' 
--AND B.CPT_DATE = A.CPT_DATE AND B.MERCHANT_NO = A.MERCHANT_NO AND B.CPT_MERCHANT_NO =A.CPT_MERCHANT_NO ),0),
--ISNULL((SELECT B.FEE_RATE FROM NCCC.TM_FEE_TYPE_DATA_D B WHERE  B.CONTRACT_TYPE = 'L1' AND B.FEE_CAL_FLG = 'AM' AND B.FEE_KIND = 'CM' 
--AND B.CPT_DATE = A.CPT_DATE AND B.MERCHANT_NO = A.MERCHANT_NO AND B.CPT_MERCHANT_NO =A.CPT_MERCHANT_NO ),0) * 100,
--ISNULL((SELECT B.FEE_AMT FROM NCCC.TM_FEE_TYPE_DATA_D B WHERE  B.CONTRACT_TYPE = 'L1' AND B.FEE_CAL_FLG = 'AM' AND B.FEE_KIND = 'CM' 
--AND B.CPT_DATE = A.CPT_DATE AND B.MERCHANT_NO = A.MERCHANT_NO AND B.CPT_MERCHANT_NO =A.CPT_MERCHANT_NO ),0),

--ISNULL((SELECT C.CPT_AMT FROM NCCC.TM_FEE_TYPE_DATA_D C WHERE  C.CONTRACT_TYPE = 'L2' AND C.FEE_CAL_FLG = 'AM' AND C.FEE_KIND = 'CM' 
--AND C.CPT_DATE = A.CPT_DATE AND C.MERCHANT_NO = A.MERCHANT_NO AND C.CPT_MERCHANT_NO =A.CPT_MERCHANT_NO ),0),
--ISNULL((SELECT C.FEE_RATE FROM NCCC.TM_FEE_TYPE_DATA_D C WHERE  C.CONTRACT_TYPE = 'L2' AND C.FEE_CAL_FLG = 'AM' AND C.FEE_KIND = 'CM' 
--AND C.CPT_DATE = A.CPT_DATE AND C.MERCHANT_NO = A.MERCHANT_NO AND C.CPT_MERCHANT_NO =A.CPT_MERCHANT_NO ),0) * 100,
--ISNULL((SELECT C.FEE_AMT FROM NCCC.TM_FEE_TYPE_DATA_D C WHERE  C.CONTRACT_TYPE = 'L2' AND C.FEE_CAL_FLG = 'AM' AND C.FEE_KIND = 'CM' 
--AND C.CPT_DATE = A.CPT_DATE AND C.MERCHANT_NO = A.MERCHANT_NO AND C.CPT_MERCHANT_NO =A.CPT_MERCHANT_NO ),0)

--FROM NCCC.TM_FEE_TYPE_DATA_D A
--LEFT JOIN GM_MERCHANT G
--ON A.CPT_MERCHANT_NO = G.MERCHANT_NO
--WHERE  A.MERCHANT_NO = '01508949' AND A.CONTRACT_TYPE = 'P1' AND A.FEE_CAL_FLG = 'AM' AND A.FEE_KIND = 'CM'
--AND A.CPT_DATE BETWEEN @SDATE AND @EDATE
--ORDER BY A.CPT_DATE
--========================================================================================================================================

--SELECT CPT_DATE,T.MERCHANT_NO,G.MERCHANT_NAME,SUM(TRANS_CNT),
--ISNULL(SUM(P_AMT),0),
--ISNULL((SELECT A.FEE_RATE FROM NCCC.TM_FEE_TYPE_DATA_D A WHERE  A.CONTRACT_TYPE = 'P1' AND A.FEE_CAL_FLG = 'AM' AND A.FEE_KIND = 'CM' 
--AND A.CPT_DATE = T.CPT_DATE AND A.MERCHANT_NO = '01508949' AND A.CPT_MERCHANT_NO = T.MERCHANT_NO),0) * 100,
--ISNULL(SUM(dbo.fn_convertNum(P_FEE,P_NUM_PREC,P_TYPE_PREC)),0),
--ISNULL(SUM(L_AMT),0),
--ISNULL((SELECT B.FEE_RATE FROM NCCC.TM_FEE_TYPE_DATA_D B WHERE  B.CONTRACT_TYPE = 'L1' AND B.FEE_CAL_FLG = 'AM' AND B.FEE_KIND = 'CM' 
--AND B.CPT_DATE = T.CPT_DATE AND B.MERCHANT_NO = '01508949' AND  B.CPT_MERCHANT_NO = T.MERCHANT_NO ),0) * 100,
--ISNULL(SUM(dbo.fn_convertNum(L_FEE,L_NUM_PREC,L_TYPE_PREC)),0),
--ISNULL(SUM(A_AMT),0),
--ISNULL((SELECT C.FEE_RATE FROM NCCC.TM_FEE_TYPE_DATA_D C WHERE  C.CONTRACT_TYPE = 'L2' AND C.FEE_CAL_FLG = 'AM' AND C.FEE_KIND = 'CM' 
--AND C.CPT_DATE = T.CPT_DATE AND C.MERCHANT_NO = '01508949' AND C.CPT_MERCHANT_NO = T.MERCHANT_NO ),0) * 100,
--ISNULL(SUM(dbo.fn_convertNum(A_FEE,A_NUM_PREC,A_TYPE_PREC)),0)
--FROM (
--	SELECT A.CPT_DATE AS CPT_DATE ,A.CPT_MERCHANT_NO AS MERCHANT_NO ,A.TRANS_CNT,
--	A.CPT_AMT AS P_AMT,A.FEE_RATE AS P_RATE,A.FEE_AMT AS P_FEE ,
--	null AS L_AMT,null L_RATE,null AS L_FEE,
--	null AS A_AMT,null A_RATE,null AS A_FEE,
--	NUM_PREC AS P_NUM_PREC,TYPE_PREC AS P_TYPE_PREC,NULL AS L_NUM_PREC,NULL AS L_TYPE_PREC,NULL AS A_NUM_PREC,NULL AS A_TYPE_PREC
--	FROM NCCC.TM_FEE_TYPE_DATA_D A
--	WHERE  A.MERCHANT_NO = '01508949' AND A.CONTRACT_TYPE = 'P1' AND A.FEE_CAL_FLG = 'AM' AND A.FEE_KIND = 'CM'
--	AND A.CPT_DATE BETWEEN @SDATE AND @EDATE
--	UNION ALL
--	SELECT B.CPT_DATE AS CPT_DATE ,B.CPT_MERCHANT_NO AS MERCHANT_NO ,0 AS TRANS_CNT,
--	null AS P_AMT,null P_RATE,null AS P_FEE,
--	B.CPT_AMT AS L_AMT,FEE_RATE as A_RATE,B.FEE_AMT AS L_FEE ,
--	null AS A_AMT,null AS A_RATE,null AS A_FEE,
--	NULL AS P_NUM_PREC,NULL AS P_TYPE_PREC,NUM_PREC AS L_NUM_PREC,TYPE_PREC AS L_TYPE_PREC,NULL AS A_NUM_PREC,NULL AS A_TYPE_PREC
--	FROM NCCC.TM_FEE_TYPE_DATA_D B
--	WHERE  B.MERCHANT_NO = '01508949' AND B.CONTRACT_TYPE = 'L1' AND B.FEE_CAL_FLG = 'AM' AND B.FEE_KIND = 'CM' 
--	AND B.CPT_DATE BETWEEN @SDATE AND @EDATE
--	UNION ALL 
--	SELECT C.CPT_DATE AS CPT_DATE ,C.CPT_MERCHANT_NO AS MERCHANT_NO ,0 AS TRANS_CNT,
--	null AS P_AMT,null P_RATE,null AS P_FEE,
--	null AS L_AMT,null L_RATE,null AS L_FEE,
--	C.CPT_AMT AS A_AMT,C.FEE_RATE * 100 AS A_RATE,C.FEE_AMT AS A_FEE,
--	NULL AS P_NUM_PREC,NULL AS P_TYPE_PREC,NULL AS L_NUM_PREC,NULL AS L_TYPE_PREC,NUM_PREC AS A_NUM_PREC,TYPE_PREC AS A_TYPE_PREC
--	FROM NCCC.TM_FEE_TYPE_DATA_D C
--	WHERE  C.MERCHANT_NO = '01508949' AND C.CONTRACT_TYPE = 'L2' AND C.FEE_CAL_FLG = 'AM' AND C.FEE_KIND = 'CM' 
--	AND C.CPT_DATE BETWEEN @SDATE AND @EDATE
--) T 
--LEFT JOIN GM_MERCHANT G
--ON T.MERCHANT_NO = G.MERCHANT_NO
--GROUP BY CPT_DATE,T.MERCHANT_NO,G.MERCHANT_NAME
--ORDER BY CPT_DATE,T.MERCHANT_NO


SELECT CPT_DATE,T.MERCHANT_NO,G.MERCHANT_NAME,SUM(TRANS_CNT),
ISNULL(SUM(P_AMT),0),
ISNULL((SELECT A.FEE_RATE FROM {0}.TM_FEE_TYPE_DATA_D A WHERE  A.CONTRACT_TYPE = 'P1' AND A.FEE_CAL_FLG = 'AM' AND A.FEE_KIND = 'CM' 
AND A.CPT_DATE = T.CPT_DATE AND A.MERCHANT_NO = @AB_MERCHANT_NO AND A.CPT_MERCHANT_NO = T.MERCHANT_NO),0) * 100,
ISNULL(SUM(dbo.fn_convertNum(P_FEE,P_NUM_PREC,P_TYPE_PREC)),0),
ISNULL(SUM(L_AMT),0),
ISNULL((SELECT B.FEE_RATE FROM {0}.TM_FEE_TYPE_DATA_D B WHERE  B.CONTRACT_TYPE = 'L1' AND B.FEE_CAL_FLG = 'AM' AND B.FEE_KIND = 'CM' 
AND B.CPT_DATE = T.CPT_DATE AND B.MERCHANT_NO = @AB_MERCHANT_NO AND  B.CPT_MERCHANT_NO = T.MERCHANT_NO ),0) * 100,
ISNULL(SUM(dbo.fn_convertNum(L_FEE,L_NUM_PREC,L_TYPE_PREC)),0),
ISNULL(SUM(A_AMT),0),
ISNULL((SELECT C.FEE_RATE FROM {0}.TM_FEE_TYPE_DATA_D C WHERE  C.CONTRACT_TYPE = 'L2' AND C.FEE_CAL_FLG = 'AM' AND C.FEE_KIND = 'CM' 
AND C.CPT_DATE = T.CPT_DATE AND C.MERCHANT_NO = @AB_MERCHANT_NO AND C.CPT_MERCHANT_NO = T.MERCHANT_NO ),0) * 100,
ISNULL(SUM(dbo.fn_convertNum(A_FEE,A_NUM_PREC,A_TYPE_PREC)),0)
FROM (
	SELECT A.CPT_DATE AS CPT_DATE ,A.CPT_MERCHANT_NO AS MERCHANT_NO ,A.TRANS_CNT,
	A.CPT_AMT AS P_AMT,A.FEE_RATE AS P_RATE,A.FEE_AMT AS P_FEE ,
	null AS L_AMT,null L_RATE,null AS L_FEE,
	null AS A_AMT,null A_RATE,null AS A_FEE,
	NUM_PREC AS P_NUM_PREC,TYPE_PREC AS P_TYPE_PREC,NULL AS L_NUM_PREC,NULL AS L_TYPE_PREC,NULL AS A_NUM_PREC,NULL AS A_TYPE_PREC
	FROM {0}.TM_FEE_TYPE_DATA_D A
	WHERE  A.MERCHANT_NO = @AB_MERCHANT_NO AND A.CONTRACT_TYPE = 'P1' AND A.FEE_CAL_FLG = 'AM' AND A.FEE_KIND = 'CM'
	AND A.CPT_DATE BETWEEN @SDATE AND @EDATE
	UNION ALL
	SELECT B.CPT_DATE AS CPT_DATE ,B.CPT_MERCHANT_NO AS MERCHANT_NO ,0 AS TRANS_CNT,
	null AS P_AMT,null P_RATE,null AS P_FEE,
	B.CPT_AMT AS L_AMT,FEE_RATE as A_RATE,B.FEE_AMT AS L_FEE ,
	null AS A_AMT,null AS A_RATE,null AS A_FEE,
	NULL AS P_NUM_PREC,NULL AS P_TYPE_PREC,NUM_PREC AS L_NUM_PREC,TYPE_PREC AS L_TYPE_PREC,NULL AS A_NUM_PREC,NULL AS A_TYPE_PREC
	FROM {0}.TM_FEE_TYPE_DATA_D B
	WHERE  B.MERCHANT_NO = @AB_MERCHANT_NO AND B.CONTRACT_TYPE = 'L1' AND B.FEE_CAL_FLG = 'AM' AND B.FEE_KIND = 'CM' 
	AND B.CPT_DATE BETWEEN @SDATE AND @EDATE
	UNION ALL 
	SELECT C.CPT_DATE AS CPT_DATE ,C.CPT_MERCHANT_NO AS MERCHANT_NO ,0 AS TRANS_CNT,
	null AS P_AMT,null P_RATE,null AS P_FEE,
	null AS L_AMT,null L_RATE,null AS L_FEE,
	C.CPT_AMT AS A_AMT,C.FEE_RATE * 100 AS A_RATE,C.FEE_AMT AS A_FEE,
	NULL AS P_NUM_PREC,NULL AS P_TYPE_PREC,NULL AS L_NUM_PREC,NULL AS L_TYPE_PREC,NUM_PREC AS A_NUM_PREC,TYPE_PREC AS A_TYPE_PREC
	FROM {0}.TM_FEE_TYPE_DATA_D C
	WHERE  C.MERCHANT_NO = @AB_MERCHANT_NO AND C.CONTRACT_TYPE = 'L2' AND C.FEE_CAL_FLG = 'AM' AND C.FEE_KIND = 'CM' 
	AND C.CPT_DATE BETWEEN @SDATE AND @EDATE
) T 
LEFT JOIN GM_MERCHANT G
ON T.MERCHANT_NO = G.MERCHANT_NO
GROUP BY CPT_DATE,T.MERCHANT_NO,G.MERCHANT_NAME
ORDER BY CPT_DATE,T.MERCHANT_NO