DECLARE @MERC_TYPE VARCHAR(10);
DECLARE @SERVER VARCHAR(30);
DECLARE @CNT INT;
SELECT @MERC_TYPE = MERCHANT_TYPE
FROM GM_MERCHANT
WHERE MERCHANT_NO = '{1}'

SELECT @SERVER = SERVER_NAME
FROM GM_COMMON_M
WHERE MERCHANT_NO = '{1}' AND TYPE_GROUP='TRANS_DESC1'

SELECT  @CNT = COUNT(1) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TM_TXLOG_D' AND TABLE_SCHEMA = '{0}'
IF @CNT = 1 
BEGIN
SELECT 'SELECT	''{2}'' AS MERCHANT_NAME ,
		a.CPT_DATE,
		a.STORE_NO,		
		s.STO_NAME_SHORT,
		a.ICC_NO,	 
		a.REG_ID,		
        a.trans_date_txlog,	'+SELECTED_COLUMNS+
        ' AS TRANS_DESC,a.TRANS_AMT,		
         a.DIFF_FLG,		
        d.DIFF_DESC,
		''TXLOG'' AS TABLE_NAME
			
FROM '+ 
CASE SERVER_NAME WHEN '' THEN '{0}.TM_TXLOG_D a ' ELSE SERVER_NAME+'.{0}.TM_TXLOG_D a ' END 
+'left join '+CASE SERVER_NAME WHEN '' THEN '{0}.BM_DIFF_M d ' ELSE SERVER_NAME+'.{0}.BM_DIFF_M d ' END
+'on a.DIFF_FLG = d.DIFF_FLG '
+'left join '+CASE SERVER_NAME WHEN '' THEN '{0}.BM_STORE_M s ' ELSE SERVER_NAME+'.{0}.BM_STORE_M s ' END
+'on a.STORE_NO=s.STORE_NO
 left join '
+CASE SERVER_NAME WHEN '' THEN '{0}.BM_TRANS_TYPE b ' ELSE SERVER_NAME+'.{0}.BM_TRANS_TYPE b ' END
+' on a.trans_type = b.trans_type
WHERE 
a.TRANS_DATE_TXLOG like ''{4}%''
and a.ICC_NO = ''{3}''
and a.STATUS = ''S'' AND a.DIFF_FLG <> ''0000''
ORDER BY 1,2,3,4,5'
        AS SQL FROM GM_COMMON_M WHERE MERCHANT_NO='{1}' AND TYPE_GROUP='TRANS_DESC1'
END
ELSE IF @MERC_TYPE = 'MUTI_MERC' OR @SERVER <> '' OR '{0}' IN ('UBS','T02','KML') OR @CNT = 0
BEGIN
SELECT '
DECLARE @T1 TABLE(
MERCHANT_NAME VARCHAR(1),
CPT_DATE  VARCHAR(1),
STORE_NO  VARCHAR(1),		
STO_NAME_SHORT  VARCHAR(1),	
ICC_NO  VARCHAR(1), 
REG_ID  VARCHAR(1),		
trans_date_txlog  VARCHAR(1),
TRANS_DESC  VARCHAR(1),
TRANS_AMT VARCHAR(1),
DIFF_FLG  VARCHAR(1),		
DIFF_DESC  VARCHAR(1),
TABLE_NAME  VARCHAR(1))
SELECT * FROM @T1	'
AS SQL
END

