--DECLARE @AB_MERCHANT_NO VARCHAR(8) = '01508949'
--DECLARE @SDATE VARCHAR(8) = '20200409'
--DECLARE @EDATE VARCHAR(8) = '20200409'

SELECT MERCHANT_NO_ACT_M '統編',MERCHANT_STNAME '入帳特店名稱',SUM(FEE_AMT) '扣款手續費',SUM(PAY_NET) '撥付淨額'
FROM (
SELECT CPT_DATE ,
g.MERCHANT_NAME ,
g.MERCHANT_NO  ,
ga.MERCHANT_NO_ACT_M,
CASE WHEN MERCHANT_NO_ACT IS NULL THEN '***'+g.MERCHANT_STNAME 
WHEN ga.MERCHANT_STNAME IS NULL or ga.MERCHANT_STNAME = '' THEN g.MERCHANT_STNAME 
ELSE ga.MERCHANT_STNAME END AS merchant_stname,
TRANS_AMT, 
FEE_RATE * 100 FEE_RATE ,
dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC)  FEE_AMT,
TRANS_AMT-dbo.fn_convertNum(FEE_AMT,NUM_PREC,TYPE_PREC)  PAY_NET ,
REMITTANCE_DATE 
FROM {0}.TM_FEE_TYPE_DATA_D a JOIN GM_MERCHANT g
ON a.MERCHANT_NO = g.MERCHANT_NO
LEFT JOIN GM_MERCHANT_ACT ga
on a.MERCHANT_NO = ga.MERCHANT_NO
WHERE CONTRACT_TYPE = 'P1' AND FEE_CAL_FLG = 'AM' AND FEE_KIND = 'CM'
AND a.MERCHANT_NO <> @AB_MERCHANT_NO 
AND REM_TYPE IN ('A004','C001') AND SETTLE_RULE = 'D'
--AND a.MERCHANT_NO = @EXEC_MERCHANT_NO
AND CPT_DATE BETWEEN @SDATE AND @EDATE 
) T
GROUP BY MERCHANT_NO_ACT_M ,MERCHANT_STNAME, FEE_RATE 
ORDER BY MERCHANT_NO_ACT_M
